import {test,expect,type Page} from '@playwright/test';import {PrismaClient} from '@prisma/client';
import {publishApprovedManually} from '../../src/lib/telegram/publisher';
const db=new PrismaClient({datasourceUrl:process.env.TEST_DATABASE_URL});
const password=process.env.E2E_PASSWORD!;
async function login(page:Page,role='super_admin'){await page.goto('/login');await page.getByLabel('اسم المستخدم',{exact:true}).fill(role);await page.getByLabel('كلمة المرور',{exact:true}).fill(password);await page.getByRole('button',{name:'تسجيل الدخول',exact:true}).click();await expect(page).not.toHaveURL(/\/login$/);}
async function edit(page:Page,id:string,title='افتتاح حديقة عامة جديدة في بيروت',body='أعلنت البلدية افتتاح حديقة عامة جديدة في بيروت.'){
 await page.goto('/posts/qa-'+id);await page.getByRole('textbox',{name:'العنوان العربي',exact:true}).fill(title);await page.locator('textarea[name=body]').fill(body);await page.getByRole('radio',{name:'النشر دون صورة',exact:true}).check();await page.getByRole('button',{name:'حفظ التعديلات',exact:true}).click();await expect.poll(async()=>(await db.humanEditorialDraft.findUnique({where:{sourcePostId:'qa-'+id}}))?.title).toBe(title);await page.reload();await expect(page.getByRole('button',{name:'اعتماد الخبر',exact:true})).toBeEnabled();
}
async function approve(page:Page,target='TELEGRAM'){await page.getByRole('button',{name:'اعتماد الخبر',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.locator('select[name=target]').selectOption(target);await dialog.locator('input[name=confirmHuman]').check();await dialog.getByRole('button',{name:'تأكيد الاعتماد'}).click();await expect(page.getByRole('heading',{name:target==='WEB'?'معاينة النشر على الويب':'نشر الرسالة المعتمدة',exact:true})).toBeVisible();}
test.beforeEach(async({page})=>{await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());});
test.afterAll(async()=>db.$disconnect());
for(const role of ['super_admin','admin','editor'])test('role '+role+' navigation and direct URL enforcement',async({page})=>{
 await login(page,role);for(const path of ['/','/review','/approvals','/published','/posts/qa-edit']){const r=await page.goto(path);expect(r?.status(),path).toBe(200);await expect(page.locator('main')).toBeVisible();}
 for(const path of ['/sources','/settings','/events','/filtered','/logs','/system']){const r=await page.goto(path);expect(r?.status(),path).toBe(role==='editor'?403:200);}
 for(const path of ['/operations','/operations/failures','/operations/posts/qa-edit']){const r=await page.goto(path);expect(r?.status(),path).toBe(role==='super_admin'?200:403);}
});
test('invalid login, forged cookie, session persistence, logout revocation',async({page,context})=>{
 await page.goto('/review');await expect(page).toHaveURL(/\/login$/);await page.getByLabel('اسم المستخدم',{exact:true}).fill('editor');await page.getByLabel('كلمة المرور',{exact:true}).fill('wrong');await page.getByRole('button',{name:'تسجيل الدخول',exact:true}).click();await expect(page.locator('main [role=alert]')).toContainText('تعذر تسجيل الدخول');
 await login(page,'editor');const cookies=await context.cookies();const c=cookies.find(c=>c.name==='iran-dashboard-session')!;expect(c.httpOnly).toBe(true);expect(c.sameSite).toBe('Strict');await page.reload();await expect(page).not.toHaveURL(/\/login$/);await page.getByRole('button',{name:'تسجيل الخروج'}).click();await expect(page).toHaveURL(/\/login$/);await page.goto('/review');await expect(page).toHaveURL(/\/login$/);await context.addCookies([c]);await page.goto('/review');await expect(page).toHaveURL(/\/login$/);await context.addCookies([{...c,value:'a'.repeat(64)}]);await page.goto('/review');await expect(page).toHaveURL(/\/login$/);
});
test('Telegram and X source CRUD, modes, refresh, duplicate and restore',async({page})=>{
 await login(page,'admin');for(const platform of ['TELEGRAM','X']){await page.goto('/sources');const add=page.locator('form').filter({has:page.getByRole('heading',{name:'إضافة مصدر',exact:true})});await add.locator('[name=name]').fill('اختبار '+platform);await add.locator('[name=handle]').fill('qa_'+platform.toLowerCase()+'_channel');await add.locator('[name=platform]').selectOption(platform);await add.locator('[name=processingMode]').selectOption('NORMAL');await add.getByRole('button',{name:'+ إضافة المصدر',exact:true}).click();const row=page.getByRole('row').filter({hasText:'@qa_'+platform.toLowerCase()+'_channel'});await expect(row).toBeVisible();await row.locator('[name=processingMode]').selectOption('DIRECT');await row.getByRole('button',{name:'حفظ طريقة المعالجة'}).click();await page.reload();await expect(row.locator('[name=processingMode]')).toHaveValue('DIRECT');await row.locator('[name=processingMode]').selectOption('NORMAL');await row.getByRole('button',{name:'حفظ طريقة المعالجة'}).click();await row.getByRole('button',{name:'تعطيل',exact:true}).click();await expect(row.getByRole('button',{name:'تفعيل',exact:true})).toBeVisible();await row.getByRole('button',{name:'تفعيل',exact:true}).click();await row.getByRole('button',{name:'إزالة',exact:true}).click();await expect(row).toHaveCount(0);
 await add.locator('[name=name]').fill('اختبار '+platform);await add.locator('[name=handle]').fill('qa_'+platform.toLowerCase()+'_channel');await add.locator('[name=platform]').selectOption(platform);await add.getByRole('button',{name:'+ إضافة المصدر',exact:true}).click();await expect(row).toBeVisible();await page.reload();await add.locator('[name=platform]').selectOption(platform);await add.locator('[name=name]').fill('اختبار '+platform);await add.locator('[name=handle]').fill('qa_'+platform.toLowerCase()+'_channel');await add.getByRole('button',{name:'+ إضافة المصدر',exact:true}).click();await expect(add.getByRole('status')).toContainText('موجود بالفعل');expect(await db.source.count({where:{platform:platform as 'TELEGRAM'|'X',handle:'qa_'+platform.toLowerCase()+'_channel'}})).toBe(1);}
});
test('failed output edit/save/refresh, empty-note approval, queue membership, edit invalidates approval',async({page})=>{
 await login(page,'editor');const before=await db.sourcePost.findUniqueOrThrow({where:{id:'qa-edit'}});await edit(page,'edit');await page.reload();await expect(page.getByRole('textbox',{name:'العنوان العربي',exact:true})).toHaveValue('افتتاح حديقة عامة جديدة في بيروت');await approve(page);const old=await db.publication.findFirstOrThrow({where:{humanDraft:{sourcePostId:'qa-edit'}}});expect(old.status).toBe('PENDING');expect(old.attemptCount).toBe(0);await page.goto('/approvals');await expect(page.getByRole('link',{name:'افتتاح حديقة عامة جديدة في بيروت',exact:true})).toBeVisible();await page.goto('/posts/qa-edit');await page.getByRole('textbox',{name:'العنوان العربي',exact:true}).fill('افتتاح حديقة في بيروت');await page.getByRole('radio',{name:'النشر دون صورة',exact:true}).check();await page.getByRole('button',{name:'حفظ التعديلات',exact:true}).click();await expect(page.getByRole('button',{name:'اعتماد الخبر',exact:true})).toBeEnabled();expect((await db.publication.findUniqueOrThrow({where:{id:old.id}})).status).toBe('CANCELLED');expect(await db.sourcePost.findUniqueOrThrow({where:{id:'qa-edit'}})).toEqual(before);
});
test('real browser image upload, replace, remove, optional empty image; source unchanged',async({page})=>{
 await login(page,'editor');await edit(page,'media');const before=(await db.sourcePost.findUniqueOrThrow({where:{id:'qa-media'}})).metadata;const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aY9sAAAAASUVORK5CYII=','base64');
 for(let i=0;i<2;i++){const previous=(await db.humanEditorialDraft.findUniqueOrThrow({where:{sourcePostId:'qa-media'}})).publicationImageId;await page.locator('input[type=file]').setInputFiles({name:'pixel.png',mimeType:'image/png',buffer:png});await page.getByRole('button',{name:i?'تغيير الصورة':'إضافة صورة',exact:true}).click();await expect(page.getByAltText('صورة النشر الاختيارية')).toBeVisible();await expect(page.getByAltText('صورة النشر الاختيارية')).not.toHaveAttribute('src','/media/'+previous);const imageId=(await page.getByAltText('صورة النشر الاختيارية').getAttribute('src'))!.split('/').at(-1);await expect.poll(()=>page.getByAltText('صورة النشر الاختيارية').evaluate((img:HTMLImageElement)=>img.naturalWidth)).toBeGreaterThan(0);await page.getByRole('radio',{name:'استخدام هذه الصورة',exact:true}).check();await page.getByRole('button',{name:'حفظ التعديلات',exact:true}).click();await expect.poll(async()=>(await db.humanEditorialDraft.findUniqueOrThrow({where:{sourcePostId:'qa-media'}})).publicationImageId).toBe(imageId);await page.reload();await expect(page.getByAltText('صورة النشر الاختيارية')).toBeVisible();}
 await page.getByRole('button',{name:'إزالة الصورة',exact:true}).click();await page.getByRole('radio',{name:'النشر دون صورة',exact:true}).check();await page.getByRole('button',{name:'حفظ التعديلات',exact:true}).click();await expect.poll(async()=>(await db.humanEditorialDraft.findUniqueOrThrow({where:{sourcePostId:'qa-media'}})).publicationImageId).toBeNull();await page.reload();await expect(page.getByAltText('صورة النشر الاختيارية')).toHaveCount(0);await approve(page,'WEB');expect((await db.sourcePost.findUniqueOrThrow({where:{id:'qa-media'}})).metadata).toEqual(before);expect((await db.publication.findFirstOrThrow({where:{humanDraft:{sourcePostId:'qa-media'}}})).publicationImageId).toBeNull();
});
test('manual fake Telegram send, frozen title-only, repeated request cannot send, historical immutable',async({page})=>{
 await login(page,'editor');await edit(page,'send','افتتاح حديقة في بيروت','');await approve(page);const p=await db.publication.findFirstOrThrow({where:{humanDraft:{sourcePostId:'qa-send'}}});expect(p.destination).toBe('-100123');await page.locator('input[name=confirmSend]').check();await page.getByRole('button',{name:'نشر مرة واحدة على Telegram',exact:true}).click();await expect(page.getByRole('button',{name:'نشر مرة واحدة على Telegram',exact:true})).toHaveCount(0);await page.reload();const sent=await db.publication.findUniqueOrThrow({where:{id:p.id}});expect(sent.status).toBe('SENT');expect(sent.telegramMessageId).toBe('777');expect(sent.contentSnapshot).toBe(p.contentSnapshot);let sends=0;const transport=async()=>{sends++;throw Error('MUST_NOT_SEND');};await Promise.all([1,2,3].map(()=>publishApprovedManually(db,{publicationId:p.id,digest:p.idempotencyKey,destination:p.destination,confirmed:true},'offline-test',process.env,transport)));expect(sends).toBe(0);expect(await db.publicationAttempt.count({where:{publicationId:p.id}})).toBe(1);await expect(page.getByRole('textbox',{name:'العنوان العربي',exact:true})).toHaveCount(0);
});
test('manual WEB delivery remains separate from fake Telegram',async({page})=>{await login(page,'editor');await edit(page,'web','افتتاح حديقة على الويب','');await approve(page,'WEB');await page.locator('input[name=confirmSend]').check();await page.getByRole('button',{name:'نشر على الويب',exact:true}).click();await expect(page.getByRole('button',{name:'نشر على الويب',exact:true})).toHaveCount(0);const p=await db.publication.findFirstOrThrow({where:{humanDraft:{sourcePostId:'qa-web'}}});await expect.poll(async()=>(await db.publication.findUniqueOrThrow({where:{id:p.id}})).status).toBe('SENT');expect(p.telegramMessageId).toBeNull();});
test('user creation, duplicate username, update/deactivate revokes sessions',async({page})=>{
 await login(page,'admin');await page.goto('/settings');await page.getByText('+ إضافة مستخدم',{exact:true}).click();const form=page.locator('form').filter({has:page.getByRole('heading',{name:'إضافة مستخدم',exact:true})});async function fill(){await form.locator('[name=username]').fill('qa_new_user');await form.locator('[name=displayName]').fill('مستخدم جديد');await form.locator('[name=password]').fill(password);await form.locator('[name=role]').selectOption('EDITOR');}await fill();await form.getByRole('button',{name:'حفظ المستخدم'}).click();await expect(page.locator('summary').filter({hasText:'qa_new_user'})).toBeVisible();await fill();await form.getByRole('button',{name:'حفظ المستخدم'}).click();await expect(form.getByRole('status')).toContainText('مستخدم بالفعل');await page.locator('summary').filter({hasText:'qa_new_user'}).click();const update=page.locator('form').filter({has:page.getByRole('heading',{name:'تحديث مستخدم جديد',exact:true})});await update.locator('[name=role]').selectOption('ADMIN');await update.locator('[name=enabled]').uncheck();await update.getByRole('button',{name:'حفظ المستخدم'}).click();await page.reload();expect((await db.dashboardUser.findUniqueOrThrow({where:{username:'qa_new_user'}})).enabled).toBe(false);
});
test('operations read-only views, historical worker not active outage, filters and invalid pages',async({page})=>{await login(page);await page.goto('/operations');await expect(page.getByText('سجل تاريخي / عامل غير مسجل للإنتاج')).toBeVisible();for(const path of ['/operations/failures?category=validation','/review?postsPage=999999','/approvals?newsPage=bad','/events','/logs']){expect((await page.goto(path))?.status()).toBe(200);await expect(page.locator('main')).toBeVisible();}});

test('SUPER_ADMIN operations holds, source controls and settings persist with audit; no worker runs',async({page})=>{
 await login(page);await page.goto('/operations');
 for(const kind of ['PROCESSING_HOLD','PUBLISHING_HOLD','SOURCE_PROCESSING_HOLD'])for(const value of ['true','false']){
  const form=page.locator('form').filter({has:page.locator(`input[name=kind][value=${kind}]`)}).filter({has:page.locator(`input[name=target][value="${kind==='SOURCE_PROCESSING_HOLD'?'qa-source':'1'}"]`)});await form.locator('..').locator('summary').click();await form.locator('[name=confirmed]').check();await form.getByRole('button',{name:'تنفيذ التغيير'}).click();await expect.poll(async()=>kind==='SOURCE_PROCESSING_HOLD'?(await db.source.findUniqueOrThrow({where:{id:'qa-source'}})).processingPaused:(await db.appSettings.findUniqueOrThrow({where:{id:1}}))[kind==='PROCESSING_HOLD'?'processingPaused':'publishingPaused']).toBe(value==='true');await page.reload();
  if(kind==='SOURCE_PROCESSING_HOLD')expect((await db.source.findUniqueOrThrow({where:{id:'qa-source'}})).processingPaused).toBe(value==='true');else expect((await db.appSettings.findUniqueOrThrow({where:{id:1}}))[kind==='PROCESSING_HOLD'?'processingPaused':'publishingPaused']).toBe(value==='true');
 }
 await page.goto('/settings');await expect(page.locator('[name=publishingMode]')).toHaveCount(0);expect((await db.appSettings.findUniqueOrThrow({where:{id:1}})).publishingMode).toBe('REQUIRE_APPROVAL');
 await page.goto('/logs');await expect(page.getByRole('link',{name:'فتح الخبر'}).first()).toBeVisible();expect(await db.auditLog.count({where:{actor:{startsWith:'user:'}}})).toBeGreaterThan(0);
});

test('EDITOR cannot replay a captured ADMIN server action; forged cross-origin action cannot mutate',async({page,browser})=>{
 await login(page,'admin');await page.goto('/sources');const form=page.locator('form').filter({has:page.getByRole('heading',{name:'إضافة مصدر',exact:true})});await form.locator('[name=name]').fill('محاولة محظورة');await form.locator('[name=handle]').fill('qa_forbidden');
 let captured: {headers:Record<string,string>;body:Buffer}|undefined;await page.route('**/sources',async route=>{const r=route.request();if(r.method()==='POST'){captured={headers:await r.allHeaders(),body:r.postDataBuffer()!};await route.abort();}else await route.continue();});await form.getByRole('button',{name:'+ إضافة المصدر',exact:true}).click();await expect.poll(()=>!!captured).toBe(true);
 const context=await browser.newContext({baseURL:process.env.TEST_BASE_URL}),editor=await context.newPage();try{await login(editor,'editor');const headers={...captured!.headers};for(const k of ['cookie','host','content-length'])delete headers[k];await context.request.post('/sources',{headers,data:captured!.body});expect(await db.source.count({where:{handle:'qa_forbidden'}})).toBe(0);
 headers.origin='https://untrusted.invalid';await context.request.post('/sources',{headers,data:captured!.body});expect(await db.source.count({where:{handle:'qa_forbidden'}})).toBe(0);
 }finally{await context.close();}
});

test('source profile edits and editorial rejection preserve original content and audit',async({page})=>{
 await login(page,'admin');await page.goto('/sources');const row=page.getByRole('row').filter({hasText:'@qa_offline'});await row.getByText('توثيق وتصنيف المصدر',{exact:true}).click();const form=row.locator('form').filter({has:page.locator('[name=classification]')});await form.locator('[name=classification]').selectOption('NEUTRAL');await form.locator('[name=authority]').selectOption('AGENCY');await form.locator('[name=verified]').check();await form.locator('[name=evidence]').fill('توثيق اصطناعي معزول للاختبار فقط');await form.getByRole('button',{name:'حفظ التصنيف'}).click();await expect(form.getByRole('status')).toContainText('تم توثيق التصنيف');await page.reload();expect((await db.source.findUniqueOrThrow({where:{id:'qa-source'}})).editorialProfile).toMatchObject({classification:'NEUTRAL',verified:true});
 await page.goto('/posts/qa-reject');const before=await db.sourcePost.findUniqueOrThrow({where:{id:'qa-reject'}});await page.getByText('رفض الخبر',{exact:true}).click();const reject=page.locator('form').filter({has:page.locator('[name=reason]')});await reject.locator('[name=reason]').fill('غير مناسب للنشر في اختبار معزول');await reject.locator('input[type=checkbox]').check();await reject.getByRole('button',{name:'تأكيد الرفض',exact:true}).click();await expect.poll(async()=>(await db.sourcePost.findUniqueOrThrow({where:{id:'qa-reject'}})).status).toBe('REJECTED');const after=await db.sourcePost.findUniqueOrThrow({where:{id:'qa-reject'}});expect(after.originalContent).toBe(before.originalContent);expect(after.processingResult).toEqual(before.processingResult);expect(await db.publication.count({where:{humanDraft:{sourcePostId:'qa-reject'}}})).toBe(0);
});

test('SENT linked publication dominates obsolete SourcePost pending state in inspector and published feed',async({page})=>{
 await login(page);await page.goto('/operations/posts/qa-sent');const panel=page.locator('section.panel').first();await expect(panel).toContainText('منشور');await expect(panel).not.toContainText('بانتظار');await expect(page.getByText(/message_id 700/)).toBeVisible();await page.goto('/published');await expect(page.getByRole('heading',{name:'خبر منشور سابقاً',exact:true})).toBeVisible();expect((await db.sourcePost.findUniqueOrThrow({where:{id:'qa-sent'}})).status).toBe('PENDING_APPROVAL');
});
