/* eslint-disable @typescript-eslint/no-explicit-any -- Minimal in-memory Prisma transaction doubles; never production inputs. */
import test from 'node:test';
import assert from 'node:assert/strict';
import type {PrismaClient} from '@prisma/client';
import {publishWeb} from '../src/lib/web-publication';
import {humanDigest,humanText} from '../src/lib/human-editorial-contract';
import {sourceHasMedia,validateImage} from '../src/lib/publication-media';
const draft={id:'d1',title:'عنوان الخبر',body:'قال المتحدث إن الاجتماع انتهى.',revision:1,originalSnapshot:{error:'UNSUPPORTED_OUTPUT'},status:'APPROVED',approvedAt:new Date(),approvedBy:'user:1',approvalNote:'المحرر راجع المصدر والصياغة.',publicationImageId:null};
function fixture(){const p:any={id:'p1',destination:'WEB',idempotencyKey:humanDigest(draft),status:'PENDING',attemptCount:0,contentSnapshot:humanText(draft),humanDraft:{...draft},humanDraftId:'d1',newsItem:null,publicationImageId:null};let attempts=0,audits=0;let chain=Promise.resolve();const tx:any={$queryRaw:async()=>[],appSettings:{findUniqueOrThrow:async()=>({publishingMode:'REQUIRE_APPROVAL'})},publication:{findUniqueOrThrow:async()=>p,update:async({data}:any)=>Object.assign(p,data)},publicationAttempt:{create:async()=>{attempts++;}},humanEditorialDraft:{update:async()=>({})},auditLog:{create:async()=>{audits++;}}};tx.$transaction=(fn:any)=>{const promise=chain.then(()=>fn(tx));chain=promise.catch(()=>{});return promise;};return {db:tx as PrismaClient,p,count:()=>({attempts,audits})};}
test('WEB freezes text and concurrent repeats create one publication attempt without a transport',async()=>{const f=fixture();await Promise.all([1,2,3].map(()=>publishWeb(f.db,{id:'p1',digest:f.p.idempotencyKey,confirmed:true},'user:1')));assert.equal(f.p.status,'SENT');assert.equal(f.p.contentSnapshot,humanText(draft));assert.deepEqual(f.count(),{attempts:1,audits:1});assert.equal(f.p.humanDraft.originalSnapshot.error,'UNSUPPORTED_OUTPUT');assert.equal(f.p.publicationImageId,null);});
test('legacy duplicated frozen WEB preview is preserved and cannot publish without reapproval',async()=>{
 const f=fixture();f.p.humanDraft.body=f.p.humanDraft.title;
 f.p.idempotencyKey=humanDigest(f.p.humanDraft);
 const frozen=`${f.p.humanDraft.title}\n\n${f.p.humanDraft.title}`;f.p.contentSnapshot=frozen;
 await assert.rejects(publishWeb(f.db,{id:'p1',digest:f.p.idempotencyKey,confirmed:true},'user:1'),/APPROVAL_CHANGED/);
 assert.equal(f.p.contentSnapshot,frozen);assert.equal(f.count().attempts,0);
});
test('WEB rejects absent confirmation, destination changes, stale text, invalid status and image tampering',async()=>{for(const mutation of [(p:any)=>p.destination='-100123',(p:any)=>p.contentSnapshot+='changed',(p:any)=>p.humanDraft.status='DRAFT',(p:any)=>p.publicationImageId='not-approved']){const f=fixture();mutation(f.p);await assert.rejects(publishWeb(f.db,{id:'p1',digest:f.p.idempotencyKey,confirmed:true},'user:1'));assert.equal(f.count().attempts,0);}const f=fixture();await assert.rejects(publishWeb(f.db,{id:'p1',digest:f.p.idempotencyKey,confirmed:false},'user:1'));});
test('media decisions alter approval digest while legacy text-only digest remains compatible',()=>{assert.notEqual(humanDigest({...draft,publicationImageId:'image1'}),humanDigest(draft));assert.notEqual(humanDigest({...draft,mediaDecisionAt:new Date()}),humanDigest(draft));assert.equal(sourceHasMedia(null),false);assert.equal(sourceHasMedia({hasMedia:true}),true);assert.equal(sourceHasMedia({hasPhoto:true}),true);assert.equal(sourceHasMedia({hasMedia:false}),false);});
test('upload rejects active content, oversized content and MIME spoofing',()=>{assert.throws(()=>validateImage(Buffer.from('<svg onload="alert(1)"></svg>'),'image/svg+xml'));assert.throws(()=>validateImage(Buffer.alloc(3*1024*1024),'image/png'));assert.throws(()=>validateImage(Buffer.alloc(32),'image/png'));const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jF1kAAAAASUVORK5CYII=','base64');assert.equal(validateImage(png,'image/png').mime,'image/png');assert.throws(()=>validateImage(png,'image/jpeg'));});
