import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {PrismaClient} from '@prisma/client';
import {ingest,claimJob,processJob} from '../src/lib/processing/engine';import {ProcessingError} from '../src/lib/processing/contracts';import {fixture,fixtureProvider,official} from './fixtures/processing';import {changeSourceProcessingMode} from '../src/lib/source-service';import {auditStoryLinks} from '../src/lib/audit-story-links';
function database(){const url=process.env.TEST_DATABASE_URL!;assert.equal(new URL(url).hostname,'127.0.0.1');return new PrismaClient({datasourceUrl:url});}
for(const transition of ['NORMAL_TO_DIRECT','DIRECT_TO_NORMAL','DISABLE'] as const)test('in-flight source transition '+transition+' cannot commit stale editorial work',{skip:!process.env.TEST_DATABASE_URL},async()=>{
 const db=database();try{const mode=transition==='DIRECT_TO_NORMAL'?'DIRECT':'NORMAL',f=fixture(randomUUID(),'عباس عراقجي يزور طهران'),provider=fixtureProvider([f]);const s=await db.source.create({data:{platform:'TELEGRAM',name:'offline',handle:randomUUID(),url:'https://t.me/offline',processingMode:mode,editorialProfile:official}});const p=await ingest(db,s.id,{externalId:'1',url:s.url+'/1',content:f.content,publishedAt:new Date()});await db.processingJob.updateMany({where:{sourcePostId:p.id},data:{availableAt:new Date(0)}});const j=await claimJob(db,'transition');assert(j);
 await processJob(db,j,{...provider,compare:provider.compare.bind(provider),draft:provider.draft.bind(provider),understand:async(input)=>{if(transition==='DISABLE')await db.source.update({where:{id:s.id},data:{enabled:false}});else await changeSourceProcessingMode(db,s.id,mode==='NORMAL'?'DIRECT':'NORMAL','user:offline');return provider.understand(input);}},new AbortController().signal);
 const post=await db.sourcePost.findUniqueOrThrow({where:{id:p.id}});assert.equal(post.error,transition==='DISABLE'?'SOURCE_DISABLED':'SOURCE_PROCESSING_MODE_CHANGED');assert.match(JSON.stringify(post.processingResult),/PROCESSING_ERROR/);assert.equal(await db.newsItem.count({where:{evidence:{some:{sourcePostId:p.id}}}}),0);assert.equal(await db.publication.count(),0);await db.source.update({where:{id:s.id},data:{processingPaused:true}});
 }finally{await db.$disconnect();}
});
for(const failure of ['PROVIDER_STAGE_OUTCOME_REQUIRES_REVIEW','PROVIDER_RETRY_EXHAUSTED'])test(failure+' becomes terminal technical recovery, unrelated work continues',{skip:!process.env.TEST_DATABASE_URL},async()=>{
 const db=database();try{const f=fixture(randomUUID(),'عباس عراقجي يزور طهران'),provider=fixtureProvider([f]);const s=await db.source.create({data:{platform:'TELEGRAM',name:'offline',handle:randomUUID(),url:'https://t.me/offline',editorialProfile:official}});const p=await ingest(db,s.id,{externalId:'1',url:s.url+'/1',content:f.content,publishedAt:new Date()});await db.processingJob.updateMany({where:{sourcePostId:p.id},data:{availableAt:new Date(0)}});const j=await claimJob(db,'unknown');assert(j);await processJob(db,j,{...provider,compare:provider.compare.bind(provider),draft:provider.draft.bind(provider),understand:async()=>{throw new ProcessingError(failure,true);}},new AbortController().signal);
 const post=await db.sourcePost.findUniqueOrThrow({where:{id:p.id}}),job=await db.processingJob.findUniqueOrThrow({where:{id:j.id}});assert.equal(job.status,'FAILED');assert.equal(job.attemptCount,1);assert.equal(post.status,'FAILED');assert.equal(post.nextRetryAt,null);assert.match(JSON.stringify(post.processingResult),/PROCESSING_ERROR/);assert.match(JSON.stringify(post.processingResult),/MANUAL_RECOVERY_REQUIRED/);assert.doesNotMatch(JSON.stringify(post.processingResult),/UNSUPPORTED_OUTPUT/);assert.equal(await claimJob(db,'restart'),null);assert.equal(await db.auditLog.count({where:{entityId:p.id,action:'PROCESSING_PROVIDER_WAIT'}}),0);assert.equal(await db.auditLog.count({where:{entityId:p.id,action:'PROCESSING_PROVIDER_RECOVERY_REQUIRED'}}),1);
 const second=await ingest(db,s.id,{externalId:'2',url:s.url+'/2',content:'عباس عراقجي يزور بغداد',publishedAt:new Date()});await db.processingJob.updateMany({where:{sourcePostId:second.id},data:{availableAt:new Date(0)}});assert.equal((await claimJob(db,'healthy'))?.sourcePostId,second.id);await db.source.update({where:{id:s.id},data:{processingPaused:true}});
 }finally{await db.$disconnect();}
});
test('audit links resolve original draft and publication foreign keys without exposing audit payloads',{skip:!process.env.TEST_DATABASE_URL},async()=>{
 const db=database();try{const source=await db.source.create({data:{platform:'TELEGRAM',name:'audit',handle:randomUUID(),url:'https://t.me/audit'}}),p=await ingest(db,source.id,{externalId:'1',url:source.url+'/1',content:'خبر محفوظ',publishedAt:new Date()});const d=await db.humanEditorialDraft.create({data:{sourcePostId:p.id,title:'عنوان',body:'',originalSnapshot:{},editedBy:'user:test'}});const links=await auditStoryLinks(db,[{id:'1',entityType:'HumanEditorialDraft',entityId:d.id},{id:'2',entityType:'SourcePost',entityId:p.id},{id:'3',entityType:'Other',entityId:'untrusted'}]);assert.equal(links['1'],'/posts/'+p.id);assert.equal(links['2'],links['1']);assert.equal(links['3'],null);
 }finally{await db.$disconnect();}
});
