/* eslint-disable @typescript-eslint/no-explicit-any -- malformed wire fixtures intentionally vary shape */
import test from 'node:test';import assert from 'node:assert/strict';
import {GeminiLanguageProvider} from '../src/lib/processing/gemini';
import {matchCanonicalArticle} from '../src/lib/processing/canonical-matching';
import type {Candidate} from '../src/lib/processing/matcher';
const at=new Date('2026-09-26T16:00:00Z');
const candidates:Candidate[]=Array.from({length:36},(_,i)=>({id:`e${i}`,revisionId:`r${i}`,revision:1,publishedAt:at,published:false,data:{actors:[],action:null,object:null,location:null,eventTime:null,facts:[],summary:'خبر إيران'}}));
const rows=()=>candidates.map(c=>({candidateId:c.revisionId,relation:'DIFFERENT_OCCURRENCE',materialUpdate:false,conflict:false,rationale:'different'}));
async function run(output:unknown,inspect?:(b:Record<string, any>)=>void){const p=new GeminiLanguageProvider('offline',async(_u,i)=>{inspect?.(JSON.parse(String(i?.body)));return Response.json({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify(output)}]}}],usageMetadata:{promptTokenCount:1,candidatesTokenCount:1}})},()=>{},true);return matchCanonicalArticle('خبر إيران',at,candidates,r=>p.canonicalRequest(r,new AbortController().signal));}
test('36-candidate failing shape becomes constant rows schema without losing source/candidates',async()=>{assert.equal((await run({matches:rows()},b=>{const schema=b.generationConfig.responseJsonSchema;assert.equal(schema.properties.matches.type,'array');assert.deepEqual(Object.keys(schema.properties.matches.items.properties),['candidateId','relation','materialUpdate','conflict','rationale']);assert.ok(JSON.stringify(schema).length<1000);const input=JSON.parse(b.contents[0].parts[0].text);assert.equal(input.candidates.length,36);assert.equal(input.source,'خبر إيران');assert.equal(b.generationConfig.maxOutputTokens,4096);assert.deepEqual(b.generationConfig.thinkingConfig,{thinkingBudget:0});assert.match(b.systemInstruction.parts[0].text,/exactly 36 rows/);})).classification,'NEW_EVENT');});
for(const [name,rel,update,conflict,expected] of [['duplicate','SAME_OCCURRENCE',false,false,'DUPLICATE'],['update','SAME_OCCURRENCE',true,false,'MATERIAL_UPDATE'],['uncertain','UNCERTAIN',false,false,'UNCERTAIN_MATCH'],['conflict','SAME_OCCURRENCE',true,true,'UNCERTAIN_MATCH']] as const)test(name,async()=>{const r=rows();r[7]={...r[7],relation:rel,materialUpdate:update,conflict};const result=await run({matches:r.reverse()});assert.equal(result.classification,expected);assert.equal(result.candidate?.revisionId,'r7');});
for(const variant of ['missing','duplicate','unknown','malformed','extra','oldObject','empty','extraEnvelope'] as const)test(`reject ${variant}`,async()=>{const r:any[]=rows();let output:any={matches:r};if(variant==='missing')r.pop();if(variant==='duplicate')r[35]={...r[0]};if(variant==='unknown')r[0].candidateId='foreign';if(variant==='malformed')r[0].relation='SUPPORTED';if(variant==='extra')r[0].invented=true;if(variant==='oldObject')output={matches:{r0:r[0]}};if(variant==='empty')output={matches:[]};if(variant==='extraEnvelope')output.extra=true;await assert.rejects(run(output),/INVALID_COMPARISON_SCHEMA|AI_INVALID_SCHEMA/);});
test('multiple matching rows preserve uncertain classification',async()=>{const r=rows();r[0].relation=r[1].relation='SAME_OCCURRENCE';assert.equal((await run({matches:r})).classification,'UNCERTAIN_MATCH');});
