import test from 'node:test';import assert from 'node:assert/strict';
import old from './fixtures/case1-compound-false-accept.json';
import {supportedLedger} from './fixtures/fidelity-review';
import {validateFidelityReceipt,validateFidelityLedger} from '../src/lib/processing/fidelity-ledger';
import {fidelityRepairDiagnostics} from '../src/lib/processing/repair-diagnostics';
import {scopePreserved} from '../src/lib/processing/targeted-repair';
import {fixture} from './fixtures/processing';
import {recoverReview} from '../src/lib/processing/review-recovery';
const source='أقر البرلمان الإيراني قانوناً جديداً لتنظيم النقل العام في إيران.';
const body='أقر البرلمان الإيراني قانوناً جديداً يهدف إلى تنظيم وتطوير قطاع النقل العام في البلاد.';
const publication=[{id:'body:1',text:body}];
function compound(s=source){const l=supportedLedger(s,publication);l.claims[0].components=[{id:'a',excerpt:'أقر البرلمان الإيراني قانوناً جديداً يهدف إلى تنظيم',sourceUnitIds:['u1'],verdict:'SUPPORTED',explanation:'Regulation is established.'},{id:'b',excerpt:'وتطوير',sourceUnitIds:['u1'],verdict:'UNSUPPORTED',explanation:'Development purpose is not established.'},{id:'c',excerpt:'قطاع النقل العام في البلاد.',sourceUnitIds:['u1'],verdict:'SUPPORTED',explanation:'Public transportation in Iran is established.'}];Object.assign(l.claims[0],{verdict:'UNSUPPORTED'});return l;}
const candidate={publication:{title:{text:''},body:[{text:body}]}};
test('exact saved blanket receipt is insufficient unchanged',()=>{assert.throws(()=>validateFidelityReceipt(source,[{id:'title',text:'البرلمان الإيراني يقر قانوناً جديداً لتنظيم النقل العام'},...publication],old.fidelityLedger),/REVIEW_RECEIPT_INVALID/);});
test('A supported B unsupported is valid rejection and scoped repair',()=>{const l=compound();assert.doesNotThrow(()=>validateFidelityReceipt(source,publication,l));assert.throws(()=>validateFidelityLedger(source,publication,l),/INDEPENDENT_FIDELITY_FAILED/);const ds=fidelityRepairDiagnostics(l,source,fixture('c',source).understanding,candidate);assert.equal(ds.length,1);const fixed=structuredClone(candidate);fixed.publication.body[0].text=body.replace('وتطوير','');assert(scopePreserved(candidate,fixed,ds));fixed.publication.body[0].text=fixed.publication.body[0].text.replace('تنظيم','إلغاء');assert(!scopePreserved(candidate,fixed,ds));});
test('both purposes explicitly supported pass',()=>{const l=compound(body);l.claims[0].components[1].verdict='SUPPORTED';Object.assign(l.claims[0],{verdict:'SUPPORTED'});assert.doesNotThrow(()=>validateFidelityLedger(body,publication,l));});
for(const [name,s,p]of [['paraphrase','افتتح المجلس المدرسة.','دشّن المجلس المدرسة.'],['translation','The council opened the school.','افتتح المجلس المدرسة.'],['journalistic present','أقر البرلمان القانون.','البرلمان يقر القانون.']] as const)test(name+' semantic fixture accepts different wording',()=>{const ps=[{id:'title',text:p}];assert.doesNotThrow(()=>validateFidelityLedger(s,ps,supportedLedger(s,ps)));});
for(const [name,s,p] of [
 ['purpose','افتتح المجلس مدرسة.','افتتح المجلس مدرسة لتعزيز التعاون.'],
 ['consequence','افتتح المجلس مدرسة.','افتتح المجلس مدرسة فانخفضت البطالة.'],
 ['cooperation agenda','التقى الوزيران.','التقى الوزيران وبحثا التعاون الثنائي.'],
 ['attribution','افتتح المجلس مدرسة.','أفادت مصادر مجهولة بأن المجلس افتتح مدرسة.']
] as const)test('unsupported '+name+' independently assessed',()=>{const ps=[{id:'title',text:p}],l=supportedLedger(s,ps);l.claims[0].components[0].verdict='UNSUPPORTED';l.claims[0].components[0].explanation='Explicit offline semantic finding: added '+name;Object.assign(l.claims[0],{verdict:'UNSUPPORTED'});assert.throws(()=>validateFidelityLedger(s,ps,l),/INDEPENDENT_FIDELITY_FAILED/);});
for(const variant of ['missing','duplicate','bad source','outside','unsupported parent','uncertain parent'])test('receipt defect '+variant,()=>{const l=compound();if(variant==='missing')l.claims[0].components.splice(1,1);if(variant==='duplicate')l.claims[0].components[1].id='a';if(variant==='bad source')l.claims[0].components[1].sourceUnitIds=['u99'];if(variant==='outside')l.claims[0].components[1].excerpt='غير موجود';if(variant==='unsupported parent')Object.assign(l.claims[0],{verdict:'SUPPORTED'});if(variant==='uncertain parent'){l.claims[0].components[1].verdict='UNCERTAIN';Object.assign(l.claims[0],{verdict:'SUPPORTED'});}assert.throws(()=>validateFidelityReceipt(source,publication,l),/REVIEW_RECEIPT_INVALID/);assert.deepEqual(fidelityRepairDiagnostics(l,source,fixture('c',source).understanding,candidate),[]);});
test('coherent uncertainty stops without article repair',()=>{const l=compound();l.claims[0].components[1].verdict='UNCERTAIN';Object.assign(l.claims[0],{verdict:'UNCERTAIN'});assert.doesNotThrow(()=>validateFidelityReceipt(source,publication,l));assert.throws(()=>validateFidelityLedger(source,publication,l),/INDEPENDENT_FIDELITY_FAILED/);assert.deepEqual(fidelityRepairDiagnostics(l,source,fixture('c',source).understanding,candidate),[]);});
test('missing accounting uses existing receipt recovery',async()=>{let calls=0;const good=compound(body);good.claims[0].components[1].verdict='SUPPORTED';Object.assign(good.claims[0],{verdict:'SUPPORTED'});await recoverReview(async()=>++calls===1?old.fidelityLedger:good,r=>validateFidelityReceipt(body,publication,r),()=>{},()=>true);assert.equal(calls,2);});

import {checkpointCall,type CheckpointStore} from '../src/worker/checkpoints';
test('durable legacy receipt replay is never silently upgraded or regenerated',async()=>{let calls=0;const store:CheckpointStore={load:async()=>({output:old.fidelityLedger}),start:async()=>{throw Error('unexpected');},finish:async()=>{throw Error('unexpected');}};const raw=await checkpointCall(store,'same-key',async()=>{calls++;return old.fidelityLedger;});assert.equal(calls,0);assert.deepEqual(raw,old.fidelityLedger);assert.throws(()=>validateFidelityReceipt(source,publication,raw),/REVIEW_RECEIPT_INVALID/);});

test('broad rejected span cannot authorize changing overlapping supported component',()=>{const l=compound();l.claims[0].components[1].excerpt=body;const ds=fidelityRepairDiagnostics(l,source,fixture('c',source).understanding,candidate);assert.equal(ds.length,1);const bad=structuredClone(candidate);bad.publication.body[0].text=body.replace('تنظيم','إلغاء');assert(!scopePreserved(candidate,bad,ds));});
