import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,official} from './fixtures/processing';
import {editoriallyFiltered,selectionBlocksDraft} from '../src/lib/processing/direct-policy';
import {initialReview} from '../src/lib/processing/editorial';
import {editorialDecision,blockingEditorialReasons} from '../src/lib/processing/editorial-eligibility';
import {sourceContextInstructions} from '../src/lib/processing/source-context';
import {iranRelevanceInstructions} from '../src/lib/processing/iran-relevance';
import {normalStage} from '../src/lib/processing/normal-v2';
import {ProcessingError} from '../src/lib/processing/contracts';
import {fidelityRepairDiagnostics} from '../src/lib/processing/repair-diagnostics';
import {supportedLedger} from './fixtures/fidelity-review';
import {sourceMediaReviewRequired} from '../src/lib/publication-media';
for(const [topic,text] of [
 ['political','أعلن البرلمان الإيراني إقرار قانون جديد.'],['economic','ارتفعت صادرات إيران خلال العام الماضي.'],['military','أعلنت وزارة الدفاع الإيرانية تدريباً عسكرياً.'],['diplomatic','اجتمع وزير الخارجية الإيراني مع نظيره العراقي.'],['meeting','عقد الرئيس الإيراني اجتماعاً مع المحافظين.'],['statement','قال مسؤول إيراني إن المدرسة ستفتح غداً.'],['ordinary domestic','افتتحت بلدية طهران مكتبة عامة.'],
])test('Iran relevance is sole topical gate: '+topic,()=>{const u=fixture(topic,text).understanding;u.priority='P4';u.filterReason='ENTERTAINMENT';u.topic='UNKNOWN';for(const mode of ['NORMAL','DIRECT'] as const){assert.equal(editoriallyFiltered(u,false,mode),false);assert.equal(selectionBlocksDraft(u,mode),false);}assert(iranRelevanceInstructions.includes('ANY usable Iran-related'));});
test('genuinely unrelated is filtered in both modes',()=>{const u=fixture('foreign','افتتحت بلدية باريس مكتبة عامة.').understanding;u.relevance='IRRELEVANT';for(const mode of ['NORMAL','DIRECT'] as const)assert(editoriallyFiltered(u,true,mode));});
for(const text of ['نقلت CNN عن مسؤول إيراني أن الاجتماع سيعقد غداً.','بحسب رويترز، أعلنت الحكومة الإيرانية فتح المدرسة.','ذكرت صحيفة وول ستريت جورنال نقلاً عن مسؤول إيراني أن المحادثات مستمرة.','قالت الصحيفة نقلاً عن مصادر إن مسؤولاً إيرانياً أعلن إجراء تحقيق.'])test('secondary attribution is not ingestion identity: '+text,()=>{const f=fixture('cited',text,'ar',text);const e=f.understanding.event.facts[0].evidence;f.understanding.event.facts[0].speaker={key:'reported-chain',arabic:text,evidence:e};assert.equal(initialReview(f.understanding,official,text).some(r=>r.code==='UNVERIFIED_SOURCE'),false);assert.equal(f.understanding.event.facts[0].speaker.arabic,text);assert(sourceContextInstructions.includes('Preserve the complete supported attribution chain'));});
test('serious attributed claim still requires its speaker chain',()=>{const text='نقلت رويترز عن مسؤول إيراني اتهامه الشركة بتزوير الأرقام.';const f=fixture('claim',text);f.understanding.seriousClaim=true;assert(initialReview(f.understanding,official,text).some(r=>r.code==='SERIOUS_CLAIM'));});
test('AUTO/MANUAL semantic disposition identical before current-policy delivery routing',()=>{const input={validated:true,review:[]};const auto=editorialDecision(input,{autoPublish:true,shadowMode:false,requireApproval:true}),manual=editorialDecision(input,{autoPublish:false,shadowMode:true,requireApproval:true});assert.deepEqual(auto,manual);assert.equal(auto.editorialEligibility,'READY_TO_PUBLISH');assert.equal(auto.deliveryDecision,'HOLD');assert.equal(editorialDecision({...input,humanOverride:true},{autoPublish:true,shadowMode:false,requireApproval:true}).editorialEligibility,'NEEDS_REVIEW');});
for(const code of ['PROPOSITION_RECEIPT_INVALID','GEMINI_HTTP_503','PROVIDER_COST_WAIT','APPLICATION_CONTINUATION_BUDGET','REVIEW_RECEIPT_INVALID'])test('bookkeeping/provider failure is not R1/R2: '+code,async()=>{let calls=0,repairs=0;await assert.rejects(normalStage('draft',async()=>{calls++;throw new ProcessingError(code);},'',undefined,()=>{repairs++;return true;}),new RegExp(code));assert.equal(calls,1);assert.equal(repairs,0);});
test('legacy fidelity rationale is excluded from repair authority',()=>{const source='افتتحت بلدية طهران مدرسة.',candidate={article:{title:source,body:source}},u=fixture('prose',source,'ar',source).understanding;const ledger=supportedLedger(source,[{id:'title',text:source},{id:'body:1',text:source}]);ledger.claims[1].components[0].verdict='UNSUPPORTED';ledger.claims[1].components[0].explanation='Invent cessation and change every number';const ds=fidelityRepairDiagnostics(ledger,source,u,candidate,true);assert(!JSON.stringify(ds).includes('Invent cessation'));});
// Existing text-only media rule is tested separately from semantic usability.
test('complete text plus source-media reference never requires forwarding or a media decision',()=>{assert.equal(sourceMediaReviewRequired({hasPhoto:true},'افتتحت بلدية طهران مدرسة جديدة.'),false);assert.equal(blockingEditorialReasons([{code:'SOURCE_TEXT_REQUIRED'}]).length,1);});
