import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {readFileSync} from 'node:fs';import {PrismaClient} from '@prisma/client';
import {saveHumanDraft,approveHumanDraft} from '../src/lib/human-editorial';import {humanDigest} from '../src/lib/human-editorial-contract';import {publishApprovedManually} from '../src/lib/telegram/publisher';import {publishWeb} from '../src/lib/web-publication';
const env={TELEGRAM_BOT_TOKEN:'123:offline',TELEGRAM_CHAT_ID:'-100123',TELEGRAM_MANUAL_PUBLISH_ENABLED:'true',AUTO_PUBLISH:'false',SHADOW_MODE:'true',REQUIRE_APPROVAL:'true',TELEGRAM_PUBLISH_ENABLED:'false'};
test('review note is optional; responsibility and explicit destination remain required in both forms',()=>{
 const ui=readFileSync('src/components/human-editor.tsx','utf8');const note=ui.match(/<textarea name="note"[^>]*>/)![0];assert(!note.includes('required'));assert(!note.includes('minLength'));assert(note.includes('maxLength={5000}'));assert(ui.includes('name="confirmHuman" type="checkbox" required'));
 const ready=readFileSync('src/components/publication-approval.tsx','utf8');assert(ready.includes('name="confirm" required'));assert(ready.includes('<ApprovalDestination/>'));assert(ui.includes('<ApprovalDestination/>'));
 assert(readFileSync('src/components/approval-destination.tsx','utf8').includes('required defaultValue=""'));
});
for(const target of ['WEB','TELEGRAM'] as const)for(const note of [undefined,'','صححت علامات الترقيم فقط.'])test(`${target}: corrected failed item accepts ${note===undefined?'omitted':note===''?'empty':'non-empty'} note and retains explicit approval`,{skip:!process.env.TEST_DATABASE_URL},async()=>{
 const url=process.env.TEST_DATABASE_URL!;assert(['127.0.0.1','localhost'].includes(new URL(url).hostname));const db=new PrismaClient({datasourceUrl:url});let sid='',pid='',did='';
 try{
 await db.appSettings.upsert({where:{id:1},create:{id:1,publishingMode:'REQUIRE_APPROVAL'},update:{publishingMode:'REQUIRE_APPROVAL'}});
 const s=await db.source.create({data:{platform:'TELEGRAM',handle:randomUUID(),name:'offline',url:'https://t.me/offline'}});sid=s.id;
 const p=await db.sourcePost.create({data:{sourceId:sid,sourcePostId:'1',sourceUrl:'https://t.me/offline/1',originalContent:'أعلن المتحدث انتهاء الاجتماع.',sourcePublishedAt:new Date(),status:'NEEDS_REVIEW',error:'UNSUPPORTED_OUTPUT'}});pid=p.id;
 const d=await saveHumanDraft(db,{kind:'post',id:pid,revision:0,title:'أعلن المتحدث انتهاء الاجتماع.',body:''},'editor');did=d.id;
 const input={id:did,digest:humanDigest(d),confirmed:true,note};
 await assert.rejects(approveHumanDraft(db,{...input,confirmed:false},'editor',env,target),/HUMAN_RESPONSIBILITY_REQUIRED/);
 await assert.rejects(approveHumanDraft(db,{...input,note:'a'.repeat(5001)},'editor',env,target));
 const frozen=await approveHumanDraft(db,input,'editor',env,target);const approved=await db.humanEditorialDraft.findUniqueOrThrow({where:{id:did}});assert.equal(approved.approvalNote,note??'');assert.equal(approved.status,'APPROVED');assert(approved.approvedAt);assert.equal(approved.approvedBy,'editor');
 const audit=await db.auditLog.findFirstOrThrow({where:{entityId:frozen.id,action:'HUMAN_EDIT_APPROVED'}});assert.equal((audit.metadata as {note:string}).note,note??'');
 let calls=0;if(target==='WEB')await publishWeb(db,{id:frozen.id,digest:frozen.idempotencyKey,confirmed:true},'editor');else await publishApprovedManually(db,{publicationId:frozen.id,digest:frozen.idempotencyKey,destination:frozen.destination,confirmed:true},'editor',env,async()=>{calls++;return Response.json({ok:true,result:{message_id:42,chat:{id:-100123}}});});
 assert.equal(calls,target==='WEB'?0:1);assert.equal((await db.publication.findUniqueOrThrow({where:{id:frozen.id}})).status,'SENT');assert.deepEqual(await db.sourcePost.findUniqueOrThrow({where:{id:pid}}),p);
 }finally{const pubs=did?await db.publication.findMany({where:{humanDraftId:did}}):[];const ids=pubs.map(p=>p.id);await db.auditLog.deleteMany({where:{entityId:{in:[did,...ids]}}});await db.publicationAttempt.deleteMany({where:{publicationId:{in:ids}}});await db.publication.deleteMany({where:{id:{in:ids}}});if(did)await db.humanEditorialDraft.delete({where:{id:did}});if(pid)await db.sourcePost.delete({where:{id:pid}});if(sid)await db.source.delete({where:{id:sid}});await db.$disconnect();}
});
import {fixture} from './fixtures/processing';import {approvePublication,approvalDigest} from '../src/lib/telegram/publisher';
test('validated READY approval needs no general note and freezes without sending',{skip:!process.env.TEST_DATABASE_URL},async()=>{
 const url=process.env.TEST_DATABASE_URL!;assert(['127.0.0.1','localhost'].includes(new URL(url).hostname));const db=new PrismaClient({datasourceUrl:url});let sid='',pid='',eid='',nid='',pubid='';const json=(v:unknown)=>JSON.parse(JSON.stringify(v));
 try{const s=await db.source.create({data:{platform:'TELEGRAM',handle:randomUUID(),name:'offline',url:'https://t.me/offline'}});sid=s.id;const f=fixture('ready-note','قال المتحدث إن الاجتماع انتهى.','ar','قال المتحدث إن الاجتماع انتهى.');const p=await db.sourcePost.create({data:{sourceId:sid,sourcePostId:'1',sourceUrl:'https://t.me/offline/1',originalContent:f.content,sourcePublishedAt:new Date()}});pid=p.id;f.understanding.event.facts.forEach(f=>{f.evidence.sourcePostId=pid;});const e=await db.canonicalEvent.create({data:{title:f.draft.title,summary:f.draft.title,facts:json(f.understanding.event),revisions:{create:{facts:json(f.understanding.event)}}},include:{revisions:true}});eid=e.id;
 const n=await db.newsItem.create({data:{eventRevisionId:e.revisions[0].id,title:f.draft.title,arabicContent:'',status:'PENDING_APPROVAL',validationStatus:'PASSED',factualEvidence:json(f.understanding.event.facts),validationResult:json({review:[],sentenceEvidence:f.draft.sentences,editorialEligibility:'READY_TO_PUBLISH'}),evidence:{create:{sourcePostId:pid}}}});nid=n.id;
 const input={newsItemId:nid,digest:approvalDigest(n),resolutions:[]};await assert.rejects(approvePublication(db,input,'',env,'TELEGRAM'),/AUTHENTICATION/);const frozen=await approvePublication(db,input,'editor',env,'TELEGRAM');pubid=frozen.id;assert.equal(frozen.status,'PENDING');assert.equal(frozen.attemptCount,0);assert.equal(frozen.contentSnapshot,n.title);assert.equal(await db.publicationAttempt.count({where:{publicationId:pubid}}),0);
 }finally{await db.auditLog.deleteMany({where:{entityId:pubid||'none'}});if(pubid)await db.publication.delete({where:{id:pubid}});if(nid){await db.newsEvidence.deleteMany({where:{newsItemId:nid}});await db.newsItem.delete({where:{id:nid}});}if(eid){await db.eventRevision.deleteMany({where:{eventId:eid}});await db.canonicalEvent.delete({where:{id:eid}});}if(pid)await db.sourcePost.delete({where:{id:pid}});if(sid)await db.source.delete({where:{id:sid}});await db.$disconnect();}
});
