import test from 'node:test';import assert from 'node:assert/strict';import {PrismaClient,ProcessingStatus} from '@prisma/client';import {readFileSync} from 'node:fs';import {duplicatePage,outcomePage} from '../src/lib/processing-visibility';import {allowed} from '../src/lib/dashboard-permissions';
test('read-only processing ledger preserves authentication and existing role boundaries',()=>{assert(allowed('ADMIN','/processing'));assert(allowed('SUPER_ADMIN','/processing'));assert(!allowed('EDITOR','/processing'));const code=readFileSync('src/app/processing/page.tsx','utf8');assert(code.includes('await requireUser(true)'));assert(!code.includes('OperationControl'));assert(code.includes('IngestionSource'));assert(readFileSync('src/components/dashboard-shell.tsx','utf8').includes("['/processing','سجل المعالجة']"));});
test('durable source outcomes, pagination, exact/semantic duplicates and archive separation',{skip:!process.env.TEST_DATABASE_URL},async()=>{
 const url=process.env.TEST_DATABASE_URL!;assert.equal(new URL(url).hostname,'127.0.0.1');const db=new PrismaClient({datasourceUrl:url});
 try{
 const source=await db.source.create({data:{platform:'TELEGRAM',handle:'visibility',name:'مصدر الاختبار',url:'https://t.me/visibility',processingMode:'NORMAL'}});
 const event=await db.canonicalEvent.create({data:{title:'الخبر الأصلي',summary:'offline',facts:{},revisions:{create:{facts:{},newsItem:{create:{title:'الخبر الأصلي',status:'PUBLISHED'}}}}},include:{revisions:true}});
 const posts=[];for(const status of Object.values(ProcessingStatus))posts.push(await db.sourcePost.create({data:{sourceId:source.id,sourcePostId:String(posts.length+1),sourceUrl:source.url+'/'+(posts.length+1),originalContent:'خبر '+status,sourcePublishedAt:new Date(),status}}));
 const dup=posts.find(p=>p.status==='DUPLICATE')!;const semantic=await db.sourcePost.create({data:{sourceId:source.id,sourcePostId:'100',sourceUrl:source.url+'/100',originalContent:'صياغة مختلفة للخبر نفسه',sourcePublishedAt:new Date(),status:'DUPLICATE'}});
 for(const [p,version] of [[dup,'exact-source-v1'],[semantic,'layered-v1']] as const)await db.eventMatch.create({data:{sourcePostId:p.id,eventRevisionId:event.revisions[0].id,classification:'DUPLICATE',rationale:'دليل مطابقة محفوظ',evidence:{type:version},matcherVersion:version}});
 const failed=posts.find(p=>p.status==='FAILED')!;await db.sourcePost.update({where:{id:failed.id},data:{error:'DIRECT_MATCH_UNRESOLVED'}});await db.processingJob.create({data:{sourcePostId:failed.id,stage:'PROCESS_V1',status:'FAILED',lastError:'DIRECT_MATCH_UNRESOLVED'}});await db.eventMatch.create({data:{sourcePostId:failed.id,eventRevisionId:event.revisions[0].id,classification:'UNCERTAIN_MATCH',rationale:'مطابقة غير محسومة'}});
 const archived=await db.sourcePost.create({data:{sourceId:source.id,sourcePostId:'101',sourceUrl:source.url+'/101',originalContent:'أرشيف',sourcePublishedAt:new Date(0),status:'REJECTED',rejectionReason:'HISTORICAL_INGESTION_RETIRED'}});await db.eventMatch.create({data:{sourcePostId:archived.id,eventRevisionId:event.revisions[0].id,classification:'DUPLICATE',rationale:'historical'}});
 for(let i=0;i<61;i++)await db.sourcePost.create({data:{sourceId:source.id,sourcePostId:String(i+200),sourceUrl:source.url+'/'+(i+200),originalContent:'خبر منتظر',sourcePublishedAt:new Date(),status:'INGESTED'}});
 const first=await duplicatePage(db,1);assert.equal(first.total,2);assert(first.items.every(m=>m.sourcePost.source.handle==='visibility'&&m.eventRevision.eventId===event.id&&m.eventRevision.newsItem));assert.deepEqual((await duplicatePage(db,1)).items.map(m=>m.id),first.items.map(m=>m.id));
 const all=[];const head=await outcomePage(db,{},1);for(let page=1;page<=head.pages;page++)all.push(...(await outcomePage(db,{},page)).items);for(const p of posts)assert(all.some(row=>row.id===p.id));assert(!all.some(p=>p.id===archived.id));assert.equal(new Set(all.map(p=>p.id)).size,all.length);
 assert.equal((await outcomePage(db,{state:'historical'},1)).items[0].id,archived.id);assert((await outcomePage(db,{state:'technical'},1)).items.some(p=>p.id===failed.id));assert(!(await duplicatePage(db,1)).items.some(m=>m.sourcePostId===failed.id));
 for(const state of ['review','ready','rejected','published'])assert((await outcomePage(db,{state},1)).total>0);
 assert.equal((await outcomePage(db,{post:failed.id},1)).total,1);assert.equal((await outcomePage(db,{source:'absent'},1)).total,0);assert.equal(await db.publication.count(),0);
 }finally{await db.$disconnect();}
});
