import test from 'node:test';import assert from 'node:assert/strict';
import {sourceCoverage,validateSourceCoverage} from '../src/lib/processing/direct-publication';
import {validateSpeakerEvidence} from '../src/lib/processing/speaker-evidence';
const ev=(s:string,t:string)=>({excerpt:t,start:s.indexOf(t),end:s.indexOf(t)+t.length});
for(const marker of ['🎥 ','✅ ','⭕ ','🔹 '])test('presentation gap preserves offsets '+marker,()=>{const text='افتتح المجلس مدرسة جديدة.';const s=marker+text;const facts=[{id:'f1',evidence:ev(s,text)}];validateSourceCoverage(s,{event:{facts}},sourceCoverage(s,facts));assert.equal(facts[0].evidence.start,marker.length);});
for(const prefix of ['🎥 الرئيس ','✅ لم ','⭕ 12 ','"رويترز" نقلاً عن ','وزير الخارجية ','عنوان خبري جديد\n'])test('missing semantic coverage is not inferred from lexical gaps '+prefix,()=>{const text='افتتح المجلس مدرسة جديدة.';const s=prefix+text;const facts=[{id:'f1',evidence:ev(s,text)}];assert.throws(()=>validateSourceCoverage(s,{event:{facts}},[]),/DIRECT_MATERIAL_COVERAGE_FAILED/);});
for(const heading of ['الرئيس الإيراني أحمد سالم:','الرئيس الإيراني، أحمد سالم:'])test('explicit definite-title heading '+heading,()=>{const fact='افتتح المجلس مدرسة جديدة.';const s=heading+'\n\n'+fact;validateSpeakerEvidence(s,ev(s,fact),ev(s,'أحمد سالم'));validateSpeakerEvidence(s,ev(s,s),ev(s,'أحمد سالم'));});
test('explicit speech institution comma',()=>{const s='أعلن المجلس المحلي، أنه افتتح مدرسة جديدة.';validateSpeakerEvidence(s,ev(s,s),ev(s,'المجلس المحلي'));});
test('explicit title and name commas',()=>{const s='أكد وزير الخارجية، أحمد سالم، أن المجلس اجتمع.';validateSpeakerEvidence(s,ev(s,s),ev(s,'أحمد سالم'));});
test('punctuation alone cannot invalidate grounded speaker evidence',()=>{const s='الرئيس أحمد سالم\n\n⭕ افتتح المجلس مدرسة جديدة.';assert.doesNotThrow(()=>validateSpeakerEvidence(s,ev(s,'افتتح المجلس مدرسة جديدة.'),ev(s,'أحمد سالم')));});
test('speaker relation is semantic; invented speaker evidence is still rejected',()=>{const s='قال أحمد سالم: قابل خالد حسن في المدرسة.';assert.throws(()=>validateSpeakerEvidence(s,ev(s,s),ev(s,'شخص غير موجود')),/INVALID_EVIDENCE/);});

import fs from 'node:fs';
import {normalStage,validateNormalExtractionCoverage} from '../src/lib/processing/normal-v2';
import {minimalExtractionSchema,validateMinimalExtraction} from '../src/lib/processing/groq-extraction';
import {directMatchingUnderstanding} from '../src/lib/processing/direct-generation';
import {presentationOnly} from '../src/lib/processing/presentation-tokens';
const fixtures=JSON.parse(fs.readFileSync(new URL('./fixtures/production-acceptance-structures.json',import.meta.url),'utf8'));
const legacyExtraction=(raw:Record<string,unknown>)=>Object.fromEntries(Object.keys(minimalExtractionSchema.shape).map(k=>[k,raw[k]]));
const saved=(id:string)=>fixtures.find((f:{id:string})=>f.id===id);
test('stored media-marker response passes without another repair request',()=>{const f=saved('28361');const x=validateMinimalExtraction(legacyExtraction(f.responses[0]),f.sourceText);validateNormalExtractionCoverage(f.sourceText,x,undefined,sourceCoverage(f.sourceText,x.statements.map(f=>({...f,speaker:f.speaker?{evidence:f.speaker}:null}))));assert.throws(()=>validateMinimalExtraction(legacyExtraction(f.responses[1]),f.sourceText),/INVALID_EVIDENCE/);});
test('stored DIRECT definite title evidence reaches matching',()=>{const f=saved('119291');assert.equal(directMatchingUnderstanding(f.responses[0],f.sourceText).event.facts.length,2);});
for(const id of ['12147','119293'])test('stored repeated evidence remains ambiguous '+id,()=>{const f=saved(id);assert.throws(()=>f.mode==='DIRECT'?directMatchingUnderstanding(f.responses[0],f.sourceText):validateMinimalExtraction(legacyExtraction(f.responses[0]),f.sourceText),/AMBIGUOUS_EVIDENCE_CONTEXT|DIRECT_MATCH_INPUT_INVALID/);});
for(const id of ['44210','44212'])test('stored lexical attribution/title gap cannot be ignored '+id,()=>{const f=saved(id);const x=validateMinimalExtraction(legacyExtraction(f.responses[0]),f.sourceText);assert.throws(()=>validateNormalExtractionCoverage(f.sourceText,x),/DIRECT_MATERIAL_COVERAGE_FAILED/);});
for(const id of ['79936','79939'])test('stored grounded speaker spans are not rejected by heading grammar '+id,()=>{const f=saved(id);assert.doesNotThrow(()=>validateMinimalExtraction(legacyExtraction(f.responses[0]),f.sourceText));});
for(const id of ['19712','79940','119292'])test('stored explicit first speaker passes across source boundaries '+id,()=>{const f=saved(id),raw=f.responses[id==='79940'?1:0],s=raw.statements[0];validateSpeakerEvidence(f.sourceText,ev(f.sourceText,s.evidence.excerpt),ev(f.sourceText,s.speaker.excerpt));});
test('uncovered source qualifiers are not decorative',()=>{const f=saved('28360');assert.equal(presentationOnly(' من على منبر الأمم المتحدة: '),false);assert.equal(presentationOnly(f.sourceText),false);});
test('stored DIRECT input is grounded without claiming article equivalence',()=>{const f=saved('119294');assert.equal(directMatchingUnderstanding(f.responses[0],f.sourceText).event.facts.length,1);});
test('repair includes source-accounting diagnostics and the untrusted candidate once',async()=>{const f=saved('44210');let calls=0;await assert.rejects(normalStage('extract',async repair=>{calls++;if(repair){assert(repair.previousOutput);assert.match(repair.instructions,/untrusted/);}const raw=legacyExtraction(f.responses[0]);const x=validateMinimalExtraction(raw,f.sourceText);validateNormalExtractionCoverage(f.sourceText,x,minimalExtractionSchema.parse(raw));},f.sourceText),/AI_SCHEMA_REPAIR_FAILED/);assert.equal(calls,2);});

test('complete explicit title heading governs circle bullets without erasing attribution',()=>{const heading='الرئيس أحمد سالم';const first='افتتح المجلس مدرسة جديدة.';const second='تبدأ الدراسة غداً.';const s=heading+':\n\n⭕ '+first+'\n\n⭕ '+second;validateSpeakerEvidence(s,ev(s,second),ev(s,heading));});
test('new voice semantics are not guessed from circle-bullet syntax',()=>{const heading='الرئيس أحمد سالم';const text='تبدأ الدراسة غداً.';const s=heading+':\n⭕ قال خالد حسن: افتتحت المدرسة.\n⭕ '+text;assert.doesNotThrow(()=>validateSpeakerEvidence(s,ev(s,text),ev(s,heading)));});

import {GeminiLanguageProvider} from '../src/lib/processing/gemini';
import {ruleSet} from '../src/lib/processing/rules';
import {unknownProfile} from '../src/lib/processing/contracts';
import {editorialDecision} from '../src/lib/processing/editorial-eligibility';
for(const uncertain of ['contentType','relevance'])test('NORMAL uncertain selection stops for review, no classification or writing '+uncertain,async()=>{let calls=0;const source='افتتح المجلس مدرسة جديدة.';const p=new GeminiLanguageProvider('offline',async()=>{calls++;return Response.json({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify({coverage:[{unitId:'u1',nonFactual:true,factIds:[]}],relevance:uncertain==='relevance'?'UNCERTAIN':'POLITICAL_NEWS',contentType:uncertain==='contentType'?'UNCERTAIN':'NEWS',contentTypeEvidence:{excerpt:source,context:source},actors:[],action:null,object:null,location:null,event_time:null,statements:[]})}]}}],usageMetadata:{promptTokenCount:1,candidatesTokenCount:1}})});await assert.rejects(p.understand({content:source,profile:unknownProfile,publishedAt:new Date(),rules:ruleSet},new AbortController().signal),/NEWS_ELIGIBILITY_UNCERTAIN/);assert.equal(calls,1);for(const autoPublish of [false,true])assert.equal(editorialDecision({error:'NEWS_ELIGIBILITY_UNCERTAIN'},{autoPublish,shadowMode:false,requireApproval:true}).editorialEligibility,'NEEDS_REVIEW');});
