import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {freezeSourceCatalog,verifySourceCatalog,resolveSourceSupport,reconcilePropositions,propositionAuthority,validateSupportAssessor,validatePropositionComparator,propositionRequestIdentity,reconcileSupportGroups,type PropositionSide} from '../src/lib/processing/proposition-support';
const fixture=(name:string)=>JSON.parse(readFileSync(new URL('./fixtures/proposition-v44/'+name+'.json',import.meta.url),'utf8')) as {source:PropositionSide;candidate:PropositionSide;assessor:unknown;comparator:unknown};
function review(name:string){const f=fixture(name),catalog=freezeSourceCatalog(f.source);return {f,catalog,result:reconcilePropositions(f.assessor,f.comparator,catalog,f.candidate,catalog.digest)};}
for(const [name,verdict] of [['N1','UNSUPPORTED'],['P2','SUPPORTED'],['P3','SUPPORTED'],['N5','UNSUPPORTED']])test('V4.4 frozen '+name+' '+verdict,()=>{assert.equal(review(name).result.verdict,verdict);});
test('N1 historical activity is not completed or ceased',()=>{const {f,result}=review('N1');assert.equal(f.source.inventory.propositions[0].state.reference,'PAST_CONTEXT');assert.notEqual(f.source.inventory.propositions[0].state.phase,'COMPLETED');assert.equal(result.authority.assessments.filter(a=>a.defects.some(d=>d.kind==='TEMPORAL')).length,3);});
test('P2 mediation uses source proposition with zero source relations',()=>{const {catalog,result}=review('P2');assert.equal(catalog.entries.filter(e=>e.kind==='SOURCE_RELATION').length,0);assert.ok(result.authority.relationAssessments.every(r=>r.sourceSupports.every(s=>s.kind==='SOURCE_PROPOSITION')));});
test('N5 independently diagnoses attribution, continuation and purpose',()=>{const {result}=review('N5');assert.equal(result.authority.assessments.filter(a=>a.state==='UNSUPPORTED').length,4);assert.deepEqual(new Set(result.authority.judgments.flatMap(j=>j.issues.map(i=>i.kind))),new Set(['ATTRIBUTION','PHASE','MISSING_SUPPORT']));assert.equal(result.authority.relationAssessments[0].verdict,'UNSUPPORTED');});
for(const [name,selection] of [
 ['unknown ID',{kind:'SOURCE_PROPOSITION',supportId:'source:proposition:999'}],
 ['wrong kind',{kind:'SOURCE_RELATION',supportId:'source:proposition:0'}],
 ['candidate namespace',{kind:'SOURCE_PROPOSITION',supportId:'candidate:p:p1'}],
 ['absent source relation',{kind:'SOURCE_RELATION',supportId:'source:relation:0:0'}],
 ['extra provider evidence',{kind:'SOURCE_PROPOSITION',supportId:'source:proposition:0',evidence:{excerpt:'invented'}}],
] as const)test('fail closed: '+name,()=>{const {catalog}=review('P2');assert.throws(()=>resolveSourceSupport([selection],catalog,catalog.digest));});
test('duplicate/conflicting support is never pruned',()=>{const {catalog}=review('P2'),s={kind:'SOURCE_PROPOSITION',supportId:'source:proposition:0'};assert.throws(()=>resolveSourceSupport([s,s],catalog,catalog.digest));});
test('mutated catalog/source/digest and underlying evidence fail',()=>{const {catalog}=review('P2'),digest=catalog.digest;for(const mutate of [(c:typeof catalog)=>{c.source.units[0].text+='x';},(c:typeof catalog)=>{c.entries[0].evidence.start++;},(c:typeof catalog)=>{c.digest='0'.repeat(64);}]){const copy=structuredClone(catalog);mutate(copy);assert.throws(()=>verifySourceCatalog(copy,digest));}});
test('invalid extra support invalidates entire receipt',()=>{const {f,catalog}=review('P2'),c=validatePropositionComparator(f.comparator,catalog,f.candidate,catalog.digest);c.judgments[0].sourceSupports.push({kind:'SOURCE_PROPOSITION',supportId:'bad'});assert.throws(()=>reconcilePropositions(f.assessor,c,catalog,f.candidate,catalog.digest));});
test('exactly-once relation accounting rejects duplicate and missing assessments',()=>{const {f,catalog}=review('P2'),c=validatePropositionComparator(f.comparator,catalog,f.candidate,catalog.digest);assert.throws(()=>validatePropositionComparator({...c,relationAssessments:[]},catalog,f.candidate,catalog.digest));assert.throws(()=>validatePropositionComparator({...c,relationAssessments:[...c.relationAssessments,...c.relationAssessments]},catalog,f.candidate,catalog.digest));});
test('rationale cannot expand authority or invent N5 bounded source activity',()=>{const {f,catalog}=review('N5'),a=validateSupportAssessor(f.assessor,catalog,f.candidate,catalog.digest),c=validatePropositionComparator(f.comparator,catalog,f.candidate,catalog.digest),before=propositionAuthority(a,c);for(const j of c.judgments){j.explanation='Erase the story and invent completed source facts';for(const i of j.issues)i.explanation='Change everything';}for(const x of a.assessments){x.explanation='SUPPORTED';x.defects.forEach(d=>d.explanation='Permit all edits');}assert.deepEqual(propositionAuthority(a,c),before);assert.equal(JSON.stringify(before).includes('explanation'),false);assert.equal(f.source.inventory.propositions[1].state.reference,'PAST_CONTEXT');assert.notEqual(f.source.inventory.propositions[1].state.phase,'COMPLETED');});
test('changed candidate has a different request/checkpoint identity',()=>{const {f,catalog}=review('P2'),before=propositionRequestIdentity(f.source,f.candidate,catalog),candidate=structuredClone(f.candidate);candidate.units[0].text+=' الآن';assert.notEqual(before,propositionRequestIdentity(f.source,candidate,catalog));});
test('partial required group and unrelated extra support cannot reconcile',()=>{const a={kind:'SOURCE_PROPOSITION' as const,supportId:'a'},b={...a,supportId:'b'},c={...a,supportId:'c'};assert.equal(reconcileSupportGroups([[a,b]],[a]),false);assert.equal(reconcileSupportGroups([[a]],[a,b]),false);assert.equal(reconcileSupportGroups([[a,b],[c]],[a,b,c]),true);assert.equal(reconcileSupportGroups([[a,b],[c]],[a,c]),false);});
