import fs from 'node:fs';import path from 'node:path';import {spawn,spawnSync} from 'node:child_process';import {randomBytes} from 'node:crypto';import {PrismaClient} from '@prisma/client';
const root=process.cwd(),url=new URL(process.env.TEST_DATABASE_URL||'');if(url.hostname!=='127.0.0.1')throw Error('LOOPBACK_TEST_DATABASE_REQUIRED');
const name='qa_'+Date.now(),adminUrl=new URL(url);adminUrl.pathname='/postgres';const admin=new PrismaClient({datasourceUrl:adminUrl.href});await admin.$executeRawUnsafe('CREATE DATABASE '+name);await admin.$disconnect();url.pathname='/'+name;
const dir=path.join(root,'.test-tools/e2e-app');fs.mkdirSync(dir,{recursive:true});for(const entry of ['src','prisma','public','package.json','package-lock.json','next.config.ts','tsconfig.json','next-env.d.ts','tests/e2e/network.cjs']){if(!fs.existsSync(entry))continue;fs.cpSync(entry,path.join(dir,entry),{recursive:true});}
if(!fs.existsSync(path.join(dir,'node_modules')))fs.symlinkSync(path.join(root,'node_modules'),path.join(dir,'node_modules'),'junction');
const env={...process.env,DATABASE_URL:url.href,TEST_DATABASE_URL:url.href,TEST_BASE_URL:'http://127.0.0.1:3198',E2E_PASSWORD:randomBytes(24).toString('hex'),AUTO_PUBLISH:'false',SHADOW_MODE:'true',REQUIRE_APPROVAL:'true',TELEGRAM_PUBLISH_ENABLED:'false',TELEGRAM_MANUAL_PUBLISH_ENABLED:'true',TELEGRAM_BOT_TOKEN:'123:offline',TELEGRAM_CHAT_ID:'-100123'};
for(const k of Object.keys(env))if(/API_KEY|API_HASH|TELEGRAM_SESSION|DATABASE_URL_UNPOOLED|ADMIN_PASSWORD|ADMIN_USERNAME|NEON|VERCEL|RAILWAY/.test(k))delete env[k];
const run=(args,cwd=root)=>{const r=spawnSync(process.execPath,args,{cwd,env,stdio:'inherit'});if(r.status!==0)throw Error('QA_COMMAND_FAILED');};
run(['node_modules/prisma/build/index.js','migrate','deploy']);run(['--import','tsx','tests/e2e/seed.ts']);
const log=fs.openSync(path.join(root,'.test-tools/e2e-server.log'),'w');const server=spawn(process.execPath,['--require',path.join(root,'tests/e2e/network.cjs'),path.join(root,'node_modules/next/dist/bin/next'),'dev','--webpack','--hostname','127.0.0.1','--port','3198'],{cwd:dir,env,stdio:['ignore',log,log],windowsHide:true});
try{let ready=false;for(let i=0;i<90;i++){try{if((await fetch(env.TEST_BASE_URL+'/api/health')).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,1000));}if(!ready)throw Error('QA_SERVER_NOT_READY');run(['node_modules/@playwright/test/cli.js','test',...process.argv.slice(2)]);}finally{server.kill();fs.closeSync(log);}
