import {AutoPublishPanel} from '@/components/auto-publish-panel';
import {Fragment} from 'react';
import Link from 'next/link';
import {randomUUID} from 'node:crypto';
import {requireSuperAdmin} from '@/lib/session';
import {db} from '@/lib/db';
import {operationsSnapshot,record,safeCode} from '@/lib/operations';
import {PageTitle,Badge} from '@/components/ui';
import {OperationControl} from '@/components/operation-control';
import {OperationsRefresh} from '@/components/operations-refresh';
import {date} from '@/lib/labels';
import {IRAN_NOW_STYLE_PROFILE_V1} from '@/lib/processing/iran-now-style';
import {ruleSet} from '@/lib/processing/rules';
export const maxDuration=60;
const money=(n:number)=>`$${n.toFixed(6)}`;
const duration=(n:number|null)=>n===null?'غير مقاس':`${(n/1000).toFixed(1)} ث`;
function Facts({rows}:{rows:[string,React.ReactNode][]}){return <dl className="facts">{rows.map(([name,value])=><Fragment key={name}><dt>{name}</dt><dd>{value}</dd></Fragment>)}</dl>;}
function Control(p:Omit<Parameters<typeof OperationControl>[0],'requestId'>){return <OperationControl {...p} requestId={randomUUID()}/>;}
export default async function OperationsPage(){
 await requireSuperAdmin();const s=await operationsSnapshot(db),cost=s.queue.capacity.cost;
 const flags=['AUTO_PUBLISH','SHADOW_MODE','REQUIRE_APPROVAL','TELEGRAM_PUBLISH_ENABLED'] as const;
 return <><PageTitle title="مركز العمليات" description={`قراءة فعلية حتى ${date(s.at)}. فتح الصفحة لا يعيد معالجة الأخبار ولا يرسلها.`}/><OperationsRefresh/>
 <nav className="filters">{[['alerts','التنبيهات'],['health','الصحة'],['pipeline','الأخبار'],['cost','الذكاء والكلفة'],['sources','المصادر'],['queue','المعالجة'],['publishing','النشر'],['activity','السجل']].map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav>
 <section className="panel" id="alerts"><h2>المشكلات والتنبيهات ({s.alerts.length})</h2>{!s.alerts.length?<p>لا توجد مشكلة نشطة مثبتة في المؤشرات المتاحة.</p>:s.alerts.map((a,i)=><article key={i}><strong>{a.severity} · {a.component}</strong><p>{a.message}</p><small>حالة مرصودة الآن · {a.since?date(a.since):'بداية الحالة غير مسجلة'}</small></article>)}</section>
 <section className="panel" id="health"><h2>صحة النظام وقاعدة البيانات</h2><Facts rows={[["قاعدة البيانات",`متصلة · ${s.databaseMs} ms`],["SourcePosts / الأخبار",`${s.totalPosts} / ${s.totalNews}`],["سعة المزود",`${s.queue.capacity.state} · ${s.queue.capacity.reason??'لا حاجز'}`],["إصدار لوحة التحكم",process.env.VERCEL_GIT_COMMIT_SHA??'غير متاح في البيئة'],['Style Profile',IRAN_NOW_STYLE_PROFILE_V1.version],['القواعد',ruleSet.version],['Gold Benchmark','direct-gold-v1 — نتائج الاختبار ليست مراقبة حية']]} />
 {s.workers.map(w=>{const m=record(w.metadata);return <article key={w.id}><h3><bdi>{w.id}</bdi> · <Badge value={w.state}/> {!w.production&&<small>سجل تاريخي / عامل غير مسجل للإنتاج</small>}</h3><Facts rows={[["آخر نبضة",date(w.lastSeenAt)],["بدء العملية (ليس وقت نشر)",date(w.startedAt)],['Telegram',typeof m.telegramReady==='boolean'?(m.telegramReady?'متصل':'غير جاهز'):'غير مسجل'],['أخطاء الاستطلاع',typeof m.pollErrors==='number'?m.pollErrors:'غير مسجلة'],['آخر دورة مكتملة',typeof m.lastPollCompletedAt==='string'?date(new Date(m.lastPollCompletedAt)):'غير مسجلة'],['المعالجة النشطة',typeof m.processingCount==='number'?m.processingCount:'غير مسجلة'],['إصدار العامل',typeof m.commit==='string'?m.commit:'غير مسجل']]} /></article>;})}
 <p className="muted">حالة Railway/Vercel المباشرة ورصيد Google المدفوع غير متاحين عبر هذه الصفحة. النبضة ليست تأكيداً من منصة الاستضافة.</p><details><summary>آخر ترحيلات قاعدة البيانات المسجلة</summary>{s.migrations.map(m=><p key={m.migration_name}><bdi>{m.migration_name}</bdi> · {m.finished_at?'مطبق':m.rolled_back_at?'تراجع':'غير مكتمل'}</p>)}</details></section>
 <section className="panel" id="pipeline"><h2>ملخص أخبار اليوم</h2><p>من {date(s.today)} بتوقيت بيروت. حالات SourcePost متنافية؛ التحديثات المادية مؤشر متداخل. النشر أدناه يعد سجلات Publication مستقلة.</p><Facts rows={[["المجموع",s.totalToday],['NORMAL / DIRECT / غير مسجل',`${s.modes.NORMAL} / ${s.modes.DIRECT} / ${s.modes.UNRECORDED}`],['التحديثات المادية',s.materialUpdates]]}/>{Object.entries(s.counts).map(([status,n])=><p key={status}><Badge value={status}/> {n}</p>)}<p><Link href="/approvals">الموافقات</Link> · <Link href="/review">المراجعات</Link> · <Link href="/events">التكرار والتحديثات</Link></p></section>
 <section className="panel" id="cost"><h2>Gemini — الطلبات والكلفة</h2><p><bdi>{s.queue.capacity.resource}</bdi></p><Facts rows={[["المقاس / المحجوز / المحسوب — 24 ساعة",`${money(cost.measuredUsd)} / ${money(cost.outstandingReservedUsd)} / ${money(cost.accountedUsd)}`],['تحذير / حاجز التطبيق',`${money(cost.warningUsd)} / ${money(cost.hardLimitUsd)}`],['قاطع الكلفة',cost.circuit],['RPD / الحد',`${s.queue.capacity.quotas.rpd} / ${s.queue.capacity.limits.rpd}`],['RPM / الحد',`${s.queue.capacity.quotas.rpm} / ${s.queue.capacity.limits.rpm}`],['TPM / الحد',`${s.queue.capacity.quotas.inputTpm} / ${s.queue.capacity.limits.inputTpm}`],['سجلات المحاولة / نجاح HTTP / 429 / 5xx / حالة أخرى أو غير معروفة',`${s.usage.attempts} / ${s.usage.success} / ${s.usage.rateLimited} / ${s.usage.serverErrors} / ${s.usage.otherFailures}`],['إعادة استخدام محفوظة (ليست طلبات)',s.usage.replays],['رموز إدخال / إخراج / تفكير',`${s.usage.input} / ${s.usage.output} / ${s.usage.thinking}`],['محاولات بلا بيانات رموز',s.usage.missingUsage],['زمن الطلب الوسيط / P95',`${duration(s.usage.latency.medianMs)} / ${duration(s.usage.latency.p95Ms)}`]]}/><p>إحصاء الطلبات من AI_STAGE_USAGE خلال 24 ساعة؛ المحاولات ذات الحالة المفقودة قد تكون حُجبت قبل الشبكة؛ لا تثبت طلباً فعلياً أو نجاحاً. الكلفة تقدير التطبيق وليست فاتورة المزود. لا يوجد مزود بديل تلقائي. سقف Google الشهري $60 بحسب إعداد المالك؛ غير متحقق حياً، ومستقل عن حاجز التطبيق.</p><details><summary>الطلبات حسب المرحلة</summary>{Object.entries(s.usage.stages).map(([stage,n])=><p key={stage}><bdi>{stage}</bdi>: {n}</p>)}</details></section>
 <section className="panel" id="sources"><h2>المصادر</h2><div className="table-scroll"><table><thead><tr><th>المصدر</th><th>الحالة / المعالجة</th><th>آخر رسالة / استطلاع</th><th>اليوم</th><th>التحكم</th></tr></thead><tbody>{s.sources.map(source=><tr key={source.id}><td>{source.name}<br/><bdi>{source.handle} · {source.platform}</bdi></td><td>{source.enabled?'مفعل':'معطل'} · {source.processingMode}{source.processingPaused?' · المعالجة موقوفة':''}</td><td><bdi>{source.posts[0]?.sourcePostId??'غير مسجلة'}</bdi><br/>{source.lastPollAt?date(source.lastPollAt):'لم يسجل استطلاع'}<br/>{source.lastError}<details><summary>نقطة الاستئناف</summary><p><bdi>{typeof record(source.cursor).lastId==='number'||typeof record(source.cursor).lastId==='string'?String(record(source.cursor).lastId):'صيغة غير معروضة؛ لا تغيير على المؤشر'}</bdi></p></details></td><td>{source.postsToday}</td><td><Control kind="SOURCE_ENABLED" target={source.id} value={String(!source.enabled)} expected={String(source.enabled)} label={source.enabled?'تعطيل المصدر':'تفعيل المصدر'}/><Control kind="SOURCE_MODE" target={source.id} value={source.processingMode==='NORMAL'?'DIRECT':'NORMAL'} expected={source.processingMode} label={`تغيير إلى ${source.processingMode==='NORMAL'?'DIRECT':'NORMAL'}`}/><Control kind="SOURCE_PROCESSING_HOLD" target={source.id} value={String(!source.processingPaused)} expected={String(source.processingPaused)} label={source.processingPaused?'استئناف معالجة المصدر':'إيقاف معالجة المصدر'}/></td></tr>)}</tbody></table></div><p>الصمت وحده ليس خطأ مثبتاً. تغيير الطريقة يسري عند بدء المحاولة؛ إذا تغيرت أثناءها تُرفض نتيجة الطريقة القديمة وتُعاد الجدولة بأمان.</p></section>
 <section className="panel" id="queue"><h2>الطابور والمعالجة</h2><Facts rows={Object.entries(s.queue.counts).map(([k,v])=>[k,v] as [string,React.ReactNode])}/><Facts rows={[["أقدم PENDING (ليس بالضرورة مؤهلاً)",duration(s.queue.oldestPendingMs)],['انتظار المزود',s.queue.providerWaiting],['انتهى خلال ساعة (نجاح أو فشل)',s.queue.finishedLastHour],['زمن المحاولة الأخيرة الوسيط / P95',`${duration(s.queue.processing.medianMs)} / ${duration(s.queue.processing.p95Ms)}`]]}/><Control kind="PROCESSING_HOLD" target="1" value={String(!s.settings?.processingPaused)} expected={String(s.settings?.processingPaused??false)} label={s.settings?.processingPaused?'استئناف المطالبات الجديدة':'إيقاف المطالبات الجديدة للمعالجة'}/><p>العمليات القائمة تنتهي بأمان. الاستطلاع والحفظ لا يتوقفان.</p><Link href="/operations/failures">مركز الأخبار المتعثرة ومفتش المسار</Link></section>
 <AutoPublishPanel settings={s.settings} heartbeat={s.workers.find(w=>w.id==='telegram-publisher-worker')}/><section className="panel" id="publishing"><h2>النشر وTelegram</h2><p>ترخيص التسليم الآلي: {String(record(s.settings?.telegramAutoPolicy).state??'غير مفعل')} · سبب الإيقاف: {safeCode(record(s.settings?.telegramAutoPolicy).reason)}</p><p>منشورات يدوية/سابقة معلقة ومستبعدة من المسار الآلي: {s.legacyPending}. لا يثبت التعليق عدم وصول رسالة؛ لا تُعد إرسال حالة أُبلغ عن وصولها دون تسوية موثقة.</p><Facts rows={flags.map(k=>[k,['true','false'].includes(process.env[k]??'')?process.env[k]!:'غير مضبوط هنا'])}/><p>القيم أعلاه بيئة لوحة التحكم، وليست افتراضاً لقيم Railway. إيقاف النشر التشغيلي: {s.settings?.publishingPaused?'نعم':'لا'}</p>{s.publications.map(p=><p key={`${p.status}:${p.destination}`}><Badge value={p.status}/> · <bdi>{p.destination}</bdi>: {p._count}</p>)}<p>آخر إرسال مسجل: {s.lastSent?`${date(s.lastSent.sentAt!)} · ${s.lastSent.destination} · message_id ${s.lastSent.telegramMessageId??'WEB'}`:'لا يوجد'}</p><p>الادعاء الذري للإرسال يحمي من التكرار. PENDING ليس دليلاً على عدم وصول رسالة؛ لا توجد إعادة إرسال تلقائية أو أداة لإعادة إرسال المنشورات التاريخية.</p><Control kind="PUBLISHING_HOLD" target="1" value={String(!s.settings?.publishingPaused)} expected={String(s.settings?.publishingPaused??false)} label={s.settings?.publishingPaused?'رفع الإيقاف (لا يغير شروط الإرسال الأخرى)':'إيقاف النشر الطارئ'}/><p>يمنع المطالبات الجديدة، ولا يمكن سحب طلب إرسال سبق أن بدأ.</p></section>
 <section className="panel" id="activity"><h2>النشاط والسجل</h2><p>آخر 60 عملية مسجلة؛ لا تُعرض المدخلات الخام أو الأسرار. تغييرات الإعدادات السابقة متاحة حسب ما سُجل فعلاً.</p>{s.activity.map(a=><p key={a.id}>{date(a.createdAt)} · <bdi>{safeCode(a.action)}</bdi> · <bdi>{a.actor}</bdi> {a.change&&<small>{a.change}</small>} {a.entityType==='SourcePost'&&a.entityId&&<Link href={`/operations/posts/${a.entityId}`}>فحص المسار</Link>}</p>)}</section>
 </>;
}
