import {z} from 'zod';
const text=z.string().min(1).max(20000);
export const temporalStateSchema=z.object({
 time:z.enum(['PAST','PRESENT','FUTURE','TIMELESS','UNSPECIFIED']),
 phase:z.enum(['PLANNED','OCCURRING','COMPLETED','UNSPECIFIED']),
 continuity:z.enum(['CONTINUING','BOUNDED','UNSPECIFIED']),
 certainty:z.enum(['ASSERTED','POSSIBLE','EXPECTED','CONDITIONAL','UNSPECIFIED']),
}).strict();
export const temporalComparisonSchema=z.object({
 publicationId:text,
 sourceExcerpt:text.describe('Copy ONE SHORT CONTIGUOUS EXACT substring from this row\'s supplied original source unit. Include the words establishing time/continuity/modality and enough context to identify the activity. No abbreviation, inserted ... or …, joining separated fragments, paraphrase or translation. Do not copy from the candidate. Use another comparison for a separate proposition; explanations belong in explanation.'),
 candidateExcerpt:text.describe('Copy ONE SHORT CONTIGUOUS EXACT substring from the supplied candidate text identified by publicationId. Include its temporal qualifiers and enough context to identify the corresponding activity. No abbreviation, inserted ... or …, joining separated fragments, paraphrase or translation. Do not copy from the source. Different source/candidate wording is allowed, but each excerpt must match its OWN text exactly.'),
 explanation:text.describe('First explain independently what time/continuity the SOURCE establishes, then what the CANDIDATE asserts. Distinguish contextual/subordinate activity from the main event. Do not assume they agree.'),
 sourceState:temporalStateSchema,candidateState:temporalStateSchema,
 assessment:z.enum(['PRESERVED','CHANGED','UNCERTAIN']),
}).strict();
/** Independent semantic findings, never evidence generated by the writer. */
export const fidelityLedgerSchema=z.object({
 sourceCoverage:z.array(z.object({unitId:text,publicationIds:z.array(text),temporal:z.array(temporalComparisonSchema).max(30),disposition:z.enum(['PRESERVED','NON_MATERIAL_PRESENTATION','MISSING','UNCERTAIN']),explanation:text}).strict()).min(1).max(200),
 claims:z.array(z.object({publicationId:text,excerpt:text,sourceUnitIds:z.array(text).min(1),verdict:z.enum(['SUPPORTED','UNSUPPORTED','UNCERTAIN']),explanation:text}).strict()).min(1).max(200),
}).strict();
