/** Transcribed from both complete owner-supplied PDFs; page numbers are physical PDF pages.
 * R = unified reference (highest authority), P = Publishing Prompt v1.0, August 2026.
 * The source classification is editorial policy, not an independent factual assertion.
 */
export type Rule = { id: string; category: string; reference: string; instruction: string };
export type TermRule = Rule & { mode: "automatic" | "contextual"; from: string[]; to: string[]; condition: string };
const term = (id: string, reference: string, mode: TermRule["mode"], from: string, to: string, condition = "outside protected spans"): TermRule =>
  ({ id, reference, category: "terminology", mode, from: from.split("|"), to: to.split("|"), condition, instruction: `${from} ← ${to}` });
export const terminology: TermRule[] = [
  term("T01", "R I.1 pp2–3; P6.1 pp6–7", "automatic", "النظام الإيراني", "الجمهورية الإسلامية الإيرانية|إيران|السلطات الإيرانية|طهران"),
  term("T02", "R I.1 p2; P6.1 p6", "automatic", "المرشد الأعلى|المرشد علي خامنئي", "قائد الثورة الإسلامية في إيران السيد علي الخامنئي|الإمام الخامنئي", "supported identity; full first mention, then قائد الثورة / السيد الخامنئي"),
  term("T03", "R I.1 p2; P6.1 p6", "automatic", "آية الله الخميني|زعيم ثورة 1979", "الإمام الخميني|مؤسس الجمهورية الإسلامية الإمام الخميني"),
  term("T04", "R I.1 p2; P6.1 p6", "automatic", "ميليشيات تابعة للنظام|الحرس الثوري الإرهابي", "الحرس الثوري الإيراني|حرس الثورة الإسلامية", "IRGC identity supported"),
  term("T05", "R I.1 p2; P6.1 p6", "automatic", "فيلق القدس المصنف إرهابياً", "قوة القدس في الحرس الثوري"),
  term("T06", "R I.1 p2; P6.1 p6", "automatic", "أرتش", "الجيش الإيراني", "may explain (آرتش); do not duplicate an existing explanation"),
  term("T07", "R I.1 p2; P6.1 p6", "automatic", "مجلس النواب الإيراني", "مجلس الشورى الإسلامي|البرلمان الإيراني"),
  term("T08", "R I.1 p2; P6.1 p6", "automatic", "رئيس النظام", "الرئيس الإيراني", "name must be supported; no invented incumbent"),
  term("T09", "R I.1 p3; P6.1 p7", "automatic", "الترسانة الصاروخية المهددة|أسلحة إيران المزعزعة للاستقرار", "القدرات الدفاعية والردعية الإيرانية|البرنامج الصاروخي الإيراني"),
  term("T10", "R I.1 p3; P6.1 p7", "automatic", "الدرونز|الطائرات بدون طيار", "المسيّرات الإيرانية", "Iranian identity required by R IX factual preservation"),
  term("T11", "R I.2 p3; P6.2 p7", "automatic", "برنامج الأسلحة النووية|الطموحات النووية", "البرنامج النووي الإيراني السلمي|البرنامج النووي الإيراني", "Iranian programme; preserve attributed allegations instead of denying facts"),
  term("T12", "R I.2 p3; P6.2 p7", "automatic", "الصفقة النووية", "الاتفاق النووي|خطة العمل الشاملة المشتركة", "Iran nuclear agreement"),
  term("T13", "R I.2 p3; P6.2 p7", "automatic", "انهيار الاتفاق النووي", "الانسحاب الأميركي الأحادي من الاتفاق النووي (2018)", "only the supported 2018 withdrawal; otherwise review, never invent cause/date"),
  term("T14", "R I.2 p3; P6.2 p7", "contextual", "العقوبات الدولية", "العقوبات الأميركية الأحادية|الحصار الاقتصادي على إيران", "retain international for previous UN Security Council sanctions; authority must be known"),
  term("T15", "R I.2 p3; P6.2 p7", "automatic", "الضغط الأقصى", "سياسة «الضغط الأقصى»", "already quoted policy names stay protected"),
  term("T16", "R I.2 p3; P6.2 p7", "automatic", "مقتل علماء نوويين|وفاة علماء نوويين", "اغتيال العلماء النوويين الإيرانيين", "Iranian scientists and assassination supported; otherwise review"),
  term("T17", "R I.3 p4; P6.3 pp7–8", "contextual", "إسرائيل|الدولة الإسرائيلية", "دولة الاحتلال|الكيان الإسرائيلي|كيان الاحتلال|\"إسرائيل\"", "entity versus geography; literal quote unchanged"),
  term("T18", "R I.3 p4; P6.3 p8", "automatic", "الجيش الإسرائيلي|جيش الدفاع الإسرائيلي", "جيش الاحتلال|قوات الاحتلال"),
  term("T19", "R I.3 p4; P6.3 p8", "contextual", "إسرائيل|أراضي 48", "الأراضي الفلسطينية المحتلة|فلسطين المحتلة|الداخل المحتل", "geographical use only"),
  term("T20", "R I.3 p4; P6.3 p8", "automatic", "أورشليم|القدس عاصمة إسرائيل", "القدس المحتلة"),
  term("T21", "R I.3 p4; P6.3 p8", "contextual", "السكان الإسرائيليون|الجيران", "المستوطنون", "identified referent; news usage, not dehumanizing figurative wording"),
  term("T22", "R I.3 p4; P6.3 p8", "automatic", "التنظيمات المسلحة|الجماعات الإرهابية|المتشددون", "المقاومة الفلسطينية|فصائل المقاومة|حماس|الجهاد الإسلامي", "Palestinian faction identity supported; no generic global substitution"),
  term("T23", "R I.3 p4; P6.3 p8", "contextual", "هجوم إرهابي|اعتداء", "عملية|عملية نوعية للمقاومة", "actor established as resistance"),
  term("T24", "R I.3 p4; P6.3 p8", "contextual", "استهداف|ضربة|رد إسرائيلي", "عدوان|اعتداء", "actor established as occupation"),
  term("T25", "R I.3 p4; P6.3 p8", "contextual", "ضحايا|قتلى", "شهداء", "identified Palestinian/resistance/civilian casualties; do not guess identity"),
  term("T26", "R I.3 p4; P6.3 p8", "contextual", "ضحايا إسرائيليون|شهداء", "قتلى الاحتلال", "identified opposing actor; news register uses قتلى"),
  term("T27", "R I.3 p5; P6.3 p8", "automatic", "المعتقلون الأمنيون|السجناء", "الأسرى الفلسطينيون|الأسيرات|الأشبال الأسرى", "Palestinian prisoner identity and age/gender must be supported"),
  term("T28", "R I.3 p5; P6.3 p8", "contextual", "الرهائن", "أسرى الاحتلال لدى المقاومة", "identified opposing captives held by resistance"),
  term("T29", "R I.3 p5; P6.3 p8", "automatic", "الحرب في غزة|حرب إسرائيل وحماس|الصراع", "الإبادة الجماعية في غزة|حرب الإبادة|العدوان على غزة", "Gaza conflict referent required"),
  term("T30", "R I.3 p5; P6.3 p9", "contextual", "القيود|الإغلاق", "الحصار على غزة", "Gaza referent"),
  term("T31", "R I.3 p5; P6.3 p9", "automatic", "الضفة الغربية", "الضفة الغربية المحتلة", "first mention only; do not double suffix"),
  term("T32", "R I.3 p5; P6.3 p9", "contextual", "القدس", "تل أبيب", "metonym for occupation government, not location"),
  term("T33", "R I.4 p5; P6.4 p9", "automatic", "ميليشيا حزب الله|وكيل إيران في لبنان|حزب الله المدعوم من إيران", "حزب الله|المقاومة الإسلامية في لبنان|المقاومة"),
  term("T34", "R I.4 p5; P6.4 p9", "automatic", "زعيم حزب الله|زعيم الميليشيا", "الأمين العام لحزب الله|سماحة الأمين العام", "Hezbollah identity and current office supported; append supported name"),
  term("T35", "R I.4 p5; P6.4 p9", "automatic", "القتلى القياديون", "الشهداء القادة", "applicable actor classification, names and ranks require review"),
  term("T36", "R I.4 p5; P6.4 p9", "automatic", "المنطقة الحدودية مع إسرائيل", "الجنوب اللبناني|القرى الحدودية الجنوبية", "Lebanese geography supported"),
  term("T37", "R I.5 p6; P6.5 p9", "automatic", "الحوثيون|ميليشيا الحوثي|المتمردون", "أنصار الله|حركة أنصار الله", "Yemeni movement referent"),
  term("T38", "R I.5 p6; P6.5 p9", "contextual", "الحكومة اليمنية", "حكومة صنعاء|حكومة الإنقاذ في صنعاء", "distinguish Sanaa from Aden"),
  term("T39", "R I.5 p6; P6.5 p9", "automatic", "مسلحو الحوثي", "القوات المسلحة اليمنية (صنعاء)"),
  term("T40", "R I.5 p6; P6.5 p10", "automatic", "التحالف العربي|التحالف السعودي|عاصفة الحزم", "تحالف العدوان بقيادة السعودية|العدوان على اليمن", "Yemen referent; quoted operation name unchanged"),
  term("T41", "R I.5 p6; P6.5 p10", "automatic", "هجمات الحوثيين على السفن|القرصنة", "العمليات اليمنية إسناداً لغزة|عمليات البحر الأحمر", "supported actors/location/motive only; no inferred Gaza motive"),
  term("T42", "R I.6 p6; P6.6 p10", "contextual", "الميليشيات الموالية لإيران|الفصائل الشيعية المسلحة", "الحشد الشعبي (هيئة رسمية ضمن القوات المسلحة العراقية)", "distinguish PMF from other factions"),
  term("T43", "R I.6 p6; P6.6 p10", "automatic", "الجماعات المسلحة المدعومة من طهران", "فصائل المقاومة الإسلامية في العراق", "Iraqi factions identified"),
  term("T44", "R I.6 p6; P6.6 p10", "automatic", "النفوذ الإيراني في العراق|الهيمنة", "العلاقات الإيرانية العراقية|التكامل الإيراني العراقي", "bilateral Iraq/Iran relation; retain attributed allegations"),
  term("T45", "R I.7 p7; P6.7 p10", "automatic", "سورية", "سوريا"),
  term("T46", "R I.7 p7; P6.7 p10", "automatic", "الرئيس السوري أحمد الشرع", "رئيس المرحلة الانتقالية أحمد الشرع", "current transitional context; time-sensitive title must be verified"),
  term("T47", "R I.7 p7; P6.7 p10", "automatic", "الحكومة السورية", "الحكومة السورية الانتقالية|سلطات دمشق الانتقالية", "current transitional period, not historical"),
  term("T48", "R I.7 p7; P6.7 p10", "contextual", "الجيش السوري|الجيش العربي السوري", "قوات الإدارة الانتقالية|عناصر هيئة تحرير الشام", "current forces identity supported; historical الجيش السوري retained"),
  term("T49", "R I.8 p8; P6.8 p11", "automatic", "خادم الحرمين الشريفين", "الملك السعودي|العاهل السعودي", "supported name; do not invent incumbent"),
  term("T50", "R I.8 p8; P6.8 p11", "automatic", "صاحب السمو الملكي", "ولي العهد السعودي محمد بن سلمان", "only identified Mohammed bin Salman; other names keep office/name without honorific"),
  term("T51", "R I.8 p8; P6.8 p11", "automatic", "الخليج العربي", "الخليج|مياه الخليج|منطقة الخليج|دول الخليج", "daily coverage; historical/map/documentary uses الخليج الفارسي"),
  term("T52", "R I.8 p8; P6.8 p11", "contextual", "الخليج", "الخليج الفارسي", "historical/map/documentary only"),
  term("T53", "R I.8 p8; P6.8 p11", "automatic", "الجزيرة العربية", "شبه الجزيرة العربية", "do not duplicate شبه"),
  term("T54", "R I.8 p8; P6.8 p11", "automatic", "التقارب المؤقت|الهدنة", "الاتفاق الإيراني السعودي|اتفاق بكين", "Iran/Saudi agreement specifically"),
  term("T55", "R I.9 p9; P6.9 p11", "automatic", "أمريكا", "أميركا|الولايات المتحدة|واشنطن|الإدارة الأميركية"),
  term("T56", "R I.9 p9; P6.9 p11", "automatic", "مقتل قاسم سليماني|تصفية سليماني", "جريمة اغتيال الشهيد الفريق قاسم سليماني"),
  term("T57", "R I.9 p9; P6.9 p11", "contextual", "قوات التحالف الدولي", "القوات الأميركية في المنطقة|القواعد الأميركية", "identified US forces; preserve other coalition participants as facts"),
  term("T58", "R I.9 p9; P6.9 p11", "automatic", "الشرق الأوسط", "غرب آسيا|غرب آسيا وشمال إفريقيا", "outside quotes, official names, documents and quoted hashtags"),
  term("T59", "R I.9 p9; P6.9 p11", "contextual", "إنذار", "تهديد", "identified opposing actor's threat"),
  term("T60", "R I.9 p9; P6.9 p11", "contextual", "الحرب على العراق", "الاحتلال الأميركي السابق للعراق", "historical US occupation referent"),
  term("T61", "R I.10 p10; P6.10 p12", "automatic", "الجزر الإماراتية المحتلة|الجزر المتنازع عليها", "الجزر الإيرانية الثلاث: أبو موسى وطنب الكبرى وطنب الصغرى", "identified three islands only"),
  term("T62", "R I.10 p10; P6.10 p12", "automatic", "مضيق هرمز الخاضع للتهديد الإيراني", "مضيق هرمز"),
  term("T63", "R I.10 p10; P6.10 p12", "automatic", "بحر الخزر", "بحر قزوين"),
  term("T64", "R I.10 p10; P6.10 p12", "contextual", "خليج عمان|خليج عُمان", "بحر عُمان", "reference specifies cartographic materials; literal quote unchanged"),
  term("T65", "R I.10 p10; P6.10 p12", "automatic", "الأحواز المحتلة|الأحواز|عربستان", "الأهواز|محافظة خوزستان"),
  term("T66", "R I.11 p10; P6.11 p12", "automatic", "تنظيم الدولة الإسلامية|الدولة الإسلامية", "داعش|تنظيم داعش الإرهابي", "ISIS identity, not any Islamic state"),
  term("T67", "R I.11 p10; P6.11 p12", "contextual", "المعارضة السورية المسلحة", "جبهة النصرة سابقاً|هيئة تحرير الشام", "identified HTS, not all Syrian opposition"),
  term("T68", "R I.11 p10; P6.11 p12", "contextual", "مسلحون مجهولون", "المجموعات الإرهابية|الخلايا الإرهابية", "identity proven for attack within Iran; cannot change unknown into known"),
];
export const names = {
  people: ["الخامنئي", "الإمام الخميني", "مسعود بزشكيان", "إبراهيم رئيسي", "حسن روحاني", "محمود أحمدي نجاد", "محمد خاتمي", "هاشمي رفسنجاني", "عباس عراقجي", "محمد جواد ظريف", "علي لاريجاني", "محمد باقر قاليباف", "علي شمخاني", "حسين سلامي", "إسماعيل قاآني", "محمد باقري", "أمير عبد اللهيان"],
  places: ["طهران", "قم", "مشهد", "أصفهان", "شيراز", "تبريز", "الأهواز", "آبادان", "خرمشهر", "بندر عباس", "تشابهار", "كرج", "رشت", "يزد", "كرمان", "همدان", "قزوين", "زاهدان", "أرومية", "جزيرة قشم", "جزيرة كيش", "حقل بارس الجنوبي"],
  institutions: ["مجلس الشورى الإسلامي", "مجلس صيانة الدستور", "مجلس خبراء القيادة", "مجمع تشخيص مصلحة النظام", "المجلس الأعلى للأمن القومي", "منظمة الطاقة الذرية الإيرانية"],
  aliases: { "بيزشكيان": "بزشكيان", "أراغتشي": "عراقجي", "عراقتشي": "عراقجي", "غاليباف": "قاليباف", "جابهار": "تشابهار", "تشاه بهار": "تشابهار", "أورميا": "أرومية", "فارس الجنوبي": "بارس الجنوبي", "Pezeshkian": "مسعود بزشكيان", "Chabahar": "تشابهار" },
  contextualAliases: { "خامنئي": "الخامنئي", "غاني": "قاآني", "كاني": "قاآني" },
  reference: "R IV p13; P10 pp14–15; P13.2 p19",
};
export const reviewReasons = {
  UNKNOWN_NAME: ["اسم شخص أو مكان غير مدرج؛ يلزم توثيق التعريب", "P4.1 p4; R IV p13"],
  SINGLE_UNOFFICIAL_FIGURE: ["أرقام من مصدر واحد غير رسمي", "P4.2 p4; R IX.4 p18"],
  LEADER_STATUS: ["خبر وفاة أو استشهاد قيادي؛ تثبيت اللقب والرتبة مطلوب", "P4.3 p4; R III p12"],
  SENSITIVE_ACTOR: ["شأن سوري أو خليجي أو عراقي حساس؛ يلزم تدقيق هوية الجهة", "P4.4 p4"],
  SERIOUS_CLAIM: ["مزاعم أو اتهامات خطيرة؛ يلزم النسب والتدقيق", "P4.5 p4; R II p11"],
  UNCOVERED_TERM: ["مصطلح غير مغطى؛ يُرفع للمسؤول التحريري", "P4.6 p4; R IX.6 p18"],
  FLAGGED_SOURCE: ["مصدر معلّم؛ تعارض بين التصفية ومثال القبول يستلزم التحقق", "P2.2 p3; P4.7 p4; P13.2 p19"],
  UNVERIFIED_SOURCE: ["لم توثق هوية المصدر أو تصنيفه", "P2.2–2.3 p3"],
  CONTEXT_REQUIRED: ["تعذر إثبات سياق الاستبدال من المصدر", "P6 p6; R IX.5–6 p18"],
  RANK_UNVERIFIED: ["الرتبة أو المنصب الحالي بحاجة إلى تثبيت", "R III p12; P9 pp13–14"],
  FIGURE_CONFLICT: ["اختلاف أرقام المصادر؛ يلزم تثبيت الرقم الرسمي مع نسبته", "P2.3 p3"],
  UNSUPPORTED_OUTPUT: ["معلومة أو صياغة غير مسندة إلى دليل المصدر", "P12.4–6 p17; R IX p18"],
  FORMAT_REVIEW: ["صيغة أو تحويل تاريخ أو عملة أو وحدة يحتاج تدقيقاً", "R V–VIII pp14–17; P11 pp16–17"],
  QUOTE_REVIEW: ["اقتباس غير متوازن أو تغير نص محمي", "R II p11; P5 p5; P8 p13"],
  UNCERTAIN_MATCH: ["مطابقة محتملة لحدث سابق؛ يلزم قرار المراجع", "User Phase2 semantic matching; P2.2 p3"],
  PROVIDER_UNAVAILABLE: ["مزود الفهم اللغوي غير مهيأ؛ لم تُنشأ صياغة آلية", "User Phase2 provider/cost boundary"],
  ARCHIVE_ONLY: ["مادة أرشيفية تُحفظ ولا تُرسل للنشر", "P3 p4"],
} as const;
export type ReviewCode = keyof typeof reviewReasons;
export const pipelineOrder = ["FILTER_AND_MATCH", "CLASSIFY", "PROTECT_QUOTES", "TERMINOLOGY_AUTOMATIC", "TERMINOLOGY_CONTEXTUAL", "ATTRIBUTION", "TITLES", "TRANSLITERATION", "SPELLING_PUNCTUATION_NUMBERS", "ASSEMBLE", "FINAL_VALIDATION", "PUBLISHING_DECISION"] as const;
export const policy: Rule[] = [
  { id: "FILTER", category: "eligibility", reference: "P2 pp2–3", instruction: "Political news related to Iran, resistance axis or West Asia. Exclude unrelated, ads, sports, entertainment, satire, unidentifiable rumours, personal opinion without approved analyst, incitement without independent news value. Approved analysis is context, not breaking news." },
  { id: "PRIORITY", category: "priority", reference: "P3 pp3–4", instruction: "P1 impactful event now: immediate editor alert; P2 daily within hour; P3 trusted context daily schedule; P4 history/geography archived without publication." },
  { id: "SOURCES", category: "sourceClassification", reference: "P2.3 p3; P3 p4", instruction: "IRAN_OFFICIAL, RESISTANCE, WESTERN, HEBREW, NEUTRAL. Authority order: Iranian official, international agency, newspaper, approved analyst. Classification is operator-verified, never inferred from a newly added handle. Official figures preferred in a conflict, always attributed." },
  { id: "QUOTE", category: "quoteProtection", reference: "R II p11; P5 p5; P8 p13", instruction: "Protect literal quotes before transforms, byte-for-byte. Protect official institution/document names and quoted source hashtags. Explicit attribution for Hebrew media; serious claims attributed in headline. Prefer short quote; longer material may be paraphrased with attribution, not fabricated as a quote." },
  { id: "ATTRIBUTION", category: "attribution", reference: "R II p11; P7 p13", instruction: "Iranian officials/resistance leaders: قال، أكد، شدد على، أوضح، أعلن، كشف عن. Opposing administrations: قال; زعم، ادّعى، روّج only unproven accusations, not every utterance. Western/Hebrew media: ذكرت، نقلت، حسب + named source. Neutral: قال، أفاد، أشار. More than one زعم/ادعى per story triggers review." },
  { id: "TITLES", category: "titles", reference: "R III p12; P9 pp13–14", instruction: "Full office/name at first mention, then short. Religious titles only supported ranks: آية الله، السيد، سماحة، حجة الإسلام والمسلمين. Verify current military ranks. الشهيد before established deceased leaders. Other countries: office/name without فخامة، صاحب السمو، خادم الحرمين. Never invent incumbent, rank or death status." },
  { id: "NAMES", category: "transliteration", reference: "R IV p13; P10 pp14–15", instruction: "Use supplied complete name/place/institution list. New name: documented Arabic IRNA/Tasnim spelling temporarily, add review request. Persian چ→تش, پ→ب, گ→غ/ك only as approved name spelling, not global text replacement." },
  { id: "SPELLING", category: "spelling", reference: "R V p14; P11.1 p16", instruction: "Hamzat wasl: اقتصاد اجتماع استشهاد استنفار انتخابات استقلال اتفاق. Hamzat qat: إيران إسناد إعلان إضراب أميركا أمين عام. قال إن، صرح بأن، أضاف أن، أكد أن. كشف عن، شدد على، أشار إلى، حذر من. أميركا، سوريا، غزة in headlines، مسيّرة/مسيّرات، ردّ when ambiguous، مياه، حياة، على، إلى، حتى. Do not change proper name علي or march مسيرة as spelling errors. No erroneous alif tanween." },
  { id: "PUNCTUATION", category: "formatting", reference: "R VI p15; P11.2 p16", instruction: "Arabic ،؛؟. No space before punctuation, space after. Parentheses for explanation; double quotes literal and إسرائيل when needed; guillemets series/operation titles. Lists use conjunction before last element. Spaced em dash. No final full stop in headline. No repeated !!/؟؟." },
  { id: "NUMBERS", category: "numbers", reference: "R VII p16; P11.3 pp16–17", instruction: "123 digits; one–ten written as words in narrative, digits in headlines/data. مليار not بليون; تريليون permitted. 20% or 20 في المئة, not بالمائة. Gregorian primary, religious Hijri optional, Solar Hijri must have Gregorian counterpart. Iranian money USD with original as needed; distinguish rial/toman (1=10). Metric units only; oil barrels/day, gas cubic metres. Conversion requires evidence, never invented rates." },
  { id: "FORMATS", category: "platformFormats", reference: "R VIII p17", instruction: "Breaking poster: عاجل |, one sentence max20 words, present verb, no explanatory parentheses, source in line for relays. Carousel: first title max2 lines/no final stop, inner slide max35 words/one idea, final summary+logo. Reel screen text follows all rules; caption news lead then context then hashtags. #إيران_الآن every publication; topical #غرب_آسيا #أنصار_الله; Instagram max5, X2–3. No media asset generation in Phase2." },
  { id: "DESCRIPTION", category: "formatting", reference: "P13.1 p19", instruction: "Do not use حلقة or برنامج as description labels. Ambiguous scope versus required البرنامج النووي: retain factual programme terminology; route unresolved description uses to review." },
  { id: "CREDIBILITY", category: "credibility", reference: "R IX p18; P12 p17", instruction: "Restrained news writing, no exaggeration; no overuse of زعم/ادعى; quotations inviolable; verify numbers before terminology; preserve facts; no unsupported information, causes, dates, identity or claims. Uncovered cases require editor and monthly rule update." },
];
export const ruleSet = {
  version: "iran-today-editorial-2026-08-v1.0.0",
  provenance: [
    { document: "مرجع المصطلحات - ايران الآن.pdf", pages: 18, precedence: 1, sha256: "942BD453A6578177D6241B457E1AD48F31C89FA2B08B588ABD244C1E0ECCF35E" },
    { document: "Publishing Prompt.pdf", pages: 19, precedence: 2, sha256: "E9475F2ACA9EBE69E6B0E19314D24E3C2D7C0018F9E7D203B1C62DDCDAE7EB8F" },
  ], duplicateWindowHours: 24, pipelineOrder, terminology, names, policy, reviewReasons,
  ambiguities: ["Flagged source: P2.2 excludes before verification while P4/P13.2 retains for review; hold, do not auto-ready.", "P13.2 Yemen example adds Gaza motive absent from source; R IX facts constraint wins, require supporting evidence.", "P13 description ban on برنامج versus nuclear programme terms: do not delete factual programme references; review ambiguous labels.", "P6 labels automatic rules whose referents/ranks/causes require evidence: store original type; uncertain context routes review.", "No verified source/analyst roster, current title registry or exchange-rate source supplied; do not invent."],
  externalPublishingEnabled: false,
};
