import {queueHealth} from '@/lib/queue-health';
import {requireUser} from "@/lib/session";
import { db } from "@/lib/db";
import { readDatabase } from "@/lib/queries";
import { workerIsStale } from "@/lib/domain";
import { date } from "@/lib/labels";
import { PageTitle, DatabaseNotice, Badge } from "@/components/ui";
export default async function SystemPage() {
 await requireUser(true);
  const result = await readDatabase(async () => {
    const [workers, jobs] = await Promise.all([db.workerHeartbeat.findMany({ orderBy: { lastSeenAt: "desc" } }), db.processingJob.groupBy({ by: ["status"], _count: true })]);
    return { workers, jobs, queue:await queueHealth(db) };
  });
  const duration=(ms:number|null)=>ms===null?'غير مقاس':`${Math.round(ms/1000)} ثانية`;
  return <><PageTitle title="حالة النظام" description="اتصال قاعدة البيانات وآخر نبضة للعامل وحالة مهام المعالجة." />{!result.available && <DatabaseNotice />}
    {result.available&&<section className="panel"><h2>صحة طابور الأخبار</h2><dl className="facts"><dt>بانتظار المعالجة</dt><dd>{result.data.queue.counts.PENDING??0}</dd><dt>عمر أقدم خبر منتظر</dt><dd>{duration(result.data.queue.oldestPendingMs)}</dd><dt>قيد المعالجة</dt><dd>{result.data.queue.counts.RUNNING??0}</dd><dt>إعادة المحاولة</dt><dd>{result.data.queue.counts.RETRY??0}</dd><dt>المهام المنتهية خلال ساعة</dt><dd>{result.data.queue.finishedLastHour}</dd><dt>انتظار الطابور — الوسيط / P95</dt><dd>{duration(result.data.queue.queueWait.medianMs)} / {duration(result.data.queue.queueWait.p95Ms)}</dd><dt>المعالجة — الوسيط / P95</dt><dd>{duration(result.data.queue.processing.medianMs)} / {duration(result.data.queue.processing.p95Ms)}</dd><dt>حالة سعة Gemini</dt><dd dir="ltr">{result.data.queue.capacity.state} {result.data.queue.capacity.reason??""}</dd><dt>مهام تنتظر سعة المزود</dt><dd>{result.data.queue.providerWaiting}</dd><dt>عمر أقدم انتظار للمزود</dt><dd>{duration(result.data.queue.oldestProviderWaitMs)}</dd><dt>طلبات الدقيقة / الحد</dt><dd>{result.data.queue.capacity.quotas.rpm} / 15</dd><dt>رموز الإدخال في الدقيقة / الحد</dt><dd>{result.data.queue.capacity.quotas.inputTpm} / 250000</dd><dt>طلبات يوم المحيط الهادئ / الحد</dt><dd>{result.data.queue.capacity.quotas.rpd} / 500</dd><dt>انتظار طلبات المزود حتى</dt><dd>{result.data.queue.cooldownUntil?date(result.data.queue.cooldownUntil):'لا يوجد'}</dd><dt>أقرب طلب جديد للمزود (لا يوقف العمل المحلي)</dt><dd>{date(result.data.queue.nextAdmission)}</dd><dt>المحاولة المجدولة التالية</dt><dd>{result.data.queue.nextRetry?date(result.data.queue.nextRetry):'لا توجد'}</dd></dl></section>}
    <section className="panel"><h2>الخدمات</h2><dl className="facts"><dt>قاعدة البيانات</dt><dd>{result.available ? "متصلة" : "غير متاحة"}</dd><dt>مراقبة Telegram وX</dt><dd>تُعرض حالة الاتصال الفعلية في نبضات العامل أدناه؛ لا يُستنتج الاتصال من فتح الصفحة</dd><dt>محرك التحرير</dt><dd>تُعرض حالات المهام أدناه؛ سلامة الصياغة تُراجع لكل خبر</dd><dt>النشر إلى Telegram</dt><dd>مسار يدوي مستقل. فتح هذه الصفحة لا يرسل أي رسالة</dd></dl></section>
    <section className="panel"><h2>العامل الخلفي</h2><p className="muted">العامل يعالج الطابور مع إعادة المحاولة. يحتاج خدمة مستقلة عن Vercel. حدّث الصفحة للحصول على أحدث حالة.</p>{result.available && !result.data.workers.length && <p>لا توجد نبضات مسجّلة. شغّل خدمة العامل.</p>}{result.data?.workers.map(worker => <article className="news-row" key={worker.id}><div className="section-title"><strong dir="ltr">{worker.id}</strong>{workerIsStale(worker.lastSeenAt, worker.intervalMs) ? <span className="badge red">النبضة متأخرة / غير متصل</span> : <Badge value={worker.state} />}</div><p>آخر نبضة: {date(worker.lastSeenAt)}</p><p className="muted">بدء التشغيل: {date(worker.startedAt)} · <bdi>{worker.phase}</bdi></p><p>جاهزية Telegram: {typeof (worker.metadata as Record<string,unknown>|null)?.telegramReady==='boolean'?((worker.metadata as Record<string,unknown>).telegramReady?'متصل':'غير جاهز'):'غير مسجلة'}</p>{worker.lastError && <p className="error-text">{worker.lastError}</p>}</article>)}</section>
    <section className="panel"><h2>مهام المعالجة</h2>{result.available && !result.data.jobs.length ? <p className="muted">لا توجد مهام معالجة.</p> : result.data?.jobs.map(job => <p key={job.status}><Badge value={job.status} /> {job._count.toLocaleString("ar")}</p>)}</section></>;
}
